window.PORRA_ODDS_LATEST = {
  "generatedAt": "2026-06-26T12:31:00Z",
  "label": "After June 25 · 60 matches · 100,000 simulations",
  "model": "Monte Carlo amb ranking FIFA + distribució empírica recent de marcadors dels Mundials, amb bonus de Pichichi proxy",
  "simulations": 100000,
  "players": [
    {
      "player": "Rafa Bravo",
      "displayName": "Rafa B.",
      "rank": 1,
      "winPct": 11.351,
      "top3Pct": 27.68,
      "lastPct": 0.0,
      "avgPoints": 884.8,
      "maxPoints": 1338,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 114.88,
      "sdGallifantes": 237.99,
      "ceGallifantes": 4.1,
      "ceRank": 2,
      "winDeltaPp": -2.773,
      "top3DeltaPp": -4.182,
      "rankDelta": 0,
      "aliases": [
        "Rafa B"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "England",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Aleix",
      "displayName": "Aleix",
      "rank": 2,
      "winPct": 11.346,
      "top3Pct": 31.237,
      "lastPct": 0.0,
      "avgPoints": 892.6,
      "maxPoints": 1238,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 2.55,
      "expectedGallifantes": 121.38,
      "sdGallifantes": 237.59,
      "ceGallifantes": 5.02,
      "ceRank": 1,
      "winDeltaPp": 0.25,
      "top3DeltaPp": 0.937,
      "rankDelta": 0,
      "projectedWinner": "Portugal",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Raphinha (8)",
      "projectedPichichiName": "Raphinha",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Bernat Raventós",
      "displayName": "Bernat R.",
      "rank": 3,
      "winPct": 6.816,
      "top3Pct": 19.953,
      "lastPct": 0.0,
      "avgPoints": 874.2,
      "maxPoints": 1308,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 74.7,
      "sdGallifantes": 193.52,
      "ceGallifantes": 2.25,
      "ceRank": 3,
      "winDeltaPp": 2.91,
      "top3DeltaPp": 7.165,
      "rankDelta": 6,
      "aliases": [
        "Bernat R"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "JoanRa",
      "displayName": "JoanRa",
      "rank": 4,
      "winPct": 6.242,
      "top3Pct": 12.896,
      "lastPct": 0.038,
      "avgPoints": 838.9,
      "maxPoints": 1189,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 2.55,
      "expectedGallifantes": 59.22,
      "sdGallifantes": 184.5,
      "ceGallifantes": 1.28,
      "ceRank": 8,
      "winDeltaPp": -1.013,
      "top3DeltaPp": -2.391,
      "rankDelta": -1,
      "projectedWinner": "Germany",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Kai Havertz (8)",
      "projectedPichichiName": "Kai Havertz",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Joan",
      "displayName": "Joan",
      "rank": 5,
      "winPct": 5.923,
      "top3Pct": 12.667,
      "lastPct": 0.017,
      "avgPoints": 833.5,
      "maxPoints": 1179,
      "pichichiPlayerPct": 51.577,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 7.74,
      "expectedGallifantes": 57.16,
      "sdGallifantes": 180.53,
      "ceGallifantes": 1.23,
      "ceRank": 9,
      "winDeltaPp": 0.349,
      "top3DeltaPp": 0.011,
      "rankDelta": 0,
      "projectedWinner": "Argentina",
      "projectedFinalist": "Germany",
      "projectedPichichi": "Messi (6)",
      "projectedPichichiName": "Messi",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Carlo",
      "displayName": "Carlo",
      "rank": 6,
      "winPct": 5.634,
      "top3Pct": 13.087,
      "lastPct": 0.0,
      "avgPoints": 858.0,
      "maxPoints": 1272,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.28,
      "expectedGallifantes": 56.1,
      "sdGallifantes": 176.8,
      "ceGallifantes": 1.3,
      "ceRank": 7,
      "winDeltaPp": 3.071,
      "top3DeltaPp": 6.098,
      "rankDelta": 5,
      "projectedWinner": "England",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Harry Kane (5)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 5
    },
    {
      "player": "Miquel",
      "displayName": "Miquel",
      "rank": 7,
      "winPct": 4.271,
      "top3Pct": 14.685,
      "lastPct": 0.001,
      "avgPoints": 869.7,
      "maxPoints": 1267,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 1.31,
      "expectedGallifantes": 50.3,
      "sdGallifantes": 158.19,
      "ceGallifantes": 1.38,
      "ceRank": 6,
      "winDeltaPp": 2.751,
      "top3DeltaPp": 8.222,
      "rankDelta": 12,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Harry Kane (7)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Pablo",
      "displayName": "Pablo",
      "rank": 8,
      "winPct": 4.261,
      "top3Pct": 16.442,
      "lastPct": 0.0,
      "avgPoints": 871.6,
      "maxPoints": 1243,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 53.92,
      "sdGallifantes": 159.47,
      "ceGallifantes": 1.61,
      "ceRank": 4,
      "winDeltaPp": -0.043,
      "top3DeltaPp": -0.04,
      "rankDelta": 0,
      "projectedWinner": "Portugal",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Rubi",
      "displayName": "Rubi",
      "rank": 9,
      "winPct": 4.141,
      "top3Pct": 12.818,
      "lastPct": 0.0,
      "avgPoints": 860.9,
      "maxPoints": 1209,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 46.32,
      "sdGallifantes": 155.12,
      "ceGallifantes": 1.19,
      "ceRank": 11,
      "winDeltaPp": -0.496,
      "top3DeltaPp": -1.223,
      "rankDelta": -2,
      "projectedWinner": "Portugal",
      "projectedFinalist": "France",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Sergi Sanromà",
      "displayName": "Sergi S.",
      "rank": 10,
      "winPct": 3.961,
      "top3Pct": 13.023,
      "lastPct": 0.0,
      "avgPoints": 864.9,
      "maxPoints": 1210,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 45.7,
      "sdGallifantes": 152.54,
      "ceGallifantes": 1.2,
      "ceRank": 10,
      "winDeltaPp": -2.037,
      "top3DeltaPp": -4.377,
      "rankDelta": -6,
      "aliases": [
        "Sergi S"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Jordi Raventós",
      "displayName": "Jordi Ra.",
      "rank": 11,
      "winPct": 3.869,
      "top3Pct": 8.84,
      "lastPct": 0.028,
      "avgPoints": 829.3,
      "maxPoints": 1197,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 38.39,
      "sdGallifantes": 148.66,
      "ceGallifantes": 0.81,
      "ceRank": 14,
      "winDeltaPp": 1.49,
      "top3DeltaPp": 3.039,
      "rankDelta": 2,
      "aliases": [
        "Jordi Ra",
        "Jordi Ra."
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Morocco",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Oscar Campanyà",
      "displayName": "Oscar C.",
      "rank": 12,
      "winPct": 2.743,
      "top3Pct": 7.877,
      "lastPct": 0.001,
      "avgPoints": 843.9,
      "maxPoints": 1184,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 30.34,
      "sdGallifantes": 128.07,
      "ceGallifantes": 0.71,
      "ceRank": 17,
      "winDeltaPp": -0.35,
      "top3DeltaPp": -0.965,
      "rankDelta": -2,
      "aliases": [
        "Oscar C"
      ],
      "projectedWinner": "Argentina",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Nicolau",
      "displayName": "Nicolau",
      "rank": 13,
      "winPct": 2.736,
      "top3Pct": 5.55,
      "lastPct": 0.221,
      "avgPoints": 803.8,
      "maxPoints": 1151,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 25.97,
      "sdGallifantes": 125.44,
      "ceGallifantes": 0.49,
      "ceRank": 22,
      "winDeltaPp": 1.563,
      "top3DeltaPp": 2.707,
      "rankDelta": 10,
      "projectedWinner": "Brazil",
      "projectedFinalist": "Netherlands",
      "projectedPichichi": "Raphinha (5)",
      "projectedPichichiName": "Raphinha",
      "projectedPichichiGoals": 5
    },
    {
      "player": "Chús",
      "displayName": "Chús",
      "rank": 14,
      "winPct": 2.659,
      "top3Pct": 8.022,
      "lastPct": 0.002,
      "avgPoints": 841.3,
      "maxPoints": 1177,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 29.63,
      "sdGallifantes": 126.05,
      "ceGallifantes": 0.71,
      "ceRank": 18,
      "winDeltaPp": -2.181,
      "top3DeltaPp": -4.679,
      "rankDelta": -8,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Ferran Torres (5)",
      "projectedPichichiName": "Ferran Torres",
      "projectedPichichiGoals": 5
    },
    {
      "player": "Emiliano",
      "displayName": "Emiliano",
      "rank": 15,
      "winPct": 2.642,
      "top3Pct": 11.694,
      "lastPct": 0.0,
      "avgPoints": 862.9,
      "maxPoints": 1242,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 35.64,
      "sdGallifantes": 128.93,
      "ceGallifantes": 1.02,
      "ceRank": 12,
      "winDeltaPp": 0.965,
      "top3DeltaPp": 3.393,
      "rankDelta": 2,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Andy",
      "displayName": "Andy",
      "rank": 16,
      "winPct": 2.371,
      "top3Pct": 6.288,
      "lastPct": 0.0,
      "avgPoints": 845.9,
      "maxPoints": 1163,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 24.97,
      "sdGallifantes": 118.42,
      "ceGallifantes": 0.57,
      "ceRank": 21,
      "winDeltaPp": 1.276,
      "top3DeltaPp": 3.304,
      "rankDelta": 9,
      "projectedWinner": "Colombia",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Juanma",
      "displayName": "Juanma",
      "rank": 17,
      "winPct": 2.244,
      "top3Pct": 9.031,
      "lastPct": 0.0,
      "avgPoints": 858.8,
      "maxPoints": 1214,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 28.67,
      "sdGallifantes": 118.42,
      "ceGallifantes": 0.75,
      "ceRank": 15,
      "winDeltaPp": 0.814,
      "top3DeltaPp": 3.157,
      "rankDelta": 3,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Oscar Bordas",
      "displayName": "Oscar B.",
      "rank": 18,
      "winPct": 1.834,
      "top3Pct": 7.383,
      "lastPct": 0.0,
      "avgPoints": 858.3,
      "maxPoints": 1223,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 23.56,
      "sdGallifantes": 107.71,
      "ceGallifantes": 0.6,
      "ceRank": 20,
      "winDeltaPp": -0.709,
      "top3DeltaPp": -2.811,
      "rankDelta": -6,
      "aliases": [
        "Oscar B"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Pol",
      "displayName": "Pol",
      "rank": 19,
      "winPct": 1.765,
      "top3Pct": 7.783,
      "lastPct": 0.001,
      "avgPoints": 855.3,
      "maxPoints": 1245,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 23.7,
      "sdGallifantes": 106.34,
      "ceGallifantes": 0.65,
      "ceRank": 19,
      "winDeltaPp": 0.482,
      "top3DeltaPp": 1.617,
      "rankDelta": 3,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Bernat Garreta",
      "displayName": "Bernat G.",
      "rank": 20,
      "winPct": 1.322,
      "top3Pct": 3.727,
      "lastPct": 0.428,
      "avgPoints": 791.4,
      "maxPoints": 1142,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.28,
      "expectedGallifantes": 14.63,
      "sdGallifantes": 90.12,
      "ceGallifantes": 0.32,
      "ceRank": 24,
      "winDeltaPp": -0.952,
      "top3DeltaPp": -1.768,
      "rankDelta": -6,
      "aliases": [
        "Bernat G"
      ],
      "projectedWinner": "England",
      "projectedFinalist": "Morocco",
      "projectedPichichi": "Harry Kane (15)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 15
    },
    {
      "player": "Guille Amor",
      "displayName": "Guille A.",
      "rank": 21,
      "winPct": 1.288,
      "top3Pct": 4.079,
      "lastPct": 0.125,
      "avgPoints": 811.8,
      "maxPoints": 1151,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.28,
      "expectedGallifantes": 15.0,
      "sdGallifantes": 89.47,
      "ceGallifantes": 0.36,
      "ceRank": 23,
      "winDeltaPp": 0.156,
      "top3DeltaPp": 0.68,
      "rankDelta": 3,
      "aliases": [
        "Guille A"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichi": "Harry Kane (6)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Antonio",
      "displayName": "Antonio",
      "rank": 22,
      "winPct": 0.971,
      "top3Pct": 3.526,
      "lastPct": 0.345,
      "avgPoints": 800.8,
      "maxPoints": 1164,
      "pichichiPlayerPct": 9.308,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.4,
      "expectedGallifantes": 12.19,
      "sdGallifantes": 78.89,
      "ceGallifantes": 0.31,
      "ceRank": 26,
      "winDeltaPp": -0.818,
      "top3DeltaPp": -2.334,
      "rankDelta": -7,
      "projectedWinner": "Argentina",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Haaland (4)",
      "projectedPichichiName": "Haaland",
      "projectedPichichiGoals": 4
    },
    {
      "player": "Bernat Orriols",
      "displayName": "Bernat O.",
      "rank": 23,
      "winPct": 0.922,
      "top3Pct": 2.751,
      "lastPct": 0.144,
      "avgPoints": 807.1,
      "maxPoints": 1187,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 3.89,
      "expectedGallifantes": 10.55,
      "sdGallifantes": 75.56,
      "ceGallifantes": 0.27,
      "ceRank": 33,
      "winDeltaPp": 0.4,
      "top3DeltaPp": 0.963,
      "rankDelta": 10,
      "aliases": [
        "Bernat O"
      ],
      "projectedWinner": "Argentina",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Mbappé (6)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Jaume Cardús",
      "displayName": "Jaume C.",
      "rank": 24,
      "winPct": 0.893,
      "top3Pct": 2.98,
      "lastPct": 0.002,
      "avgPoints": 817.8,
      "maxPoints": 1157,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 2.55,
      "expectedGallifantes": 10.96,
      "sdGallifantes": 75.13,
      "ceGallifantes": 0.31,
      "ceRank": 25,
      "winDeltaPp": -0.882,
      "top3DeltaPp": -1.861,
      "rankDelta": -8,
      "aliases": [
        "Jaume C"
      ],
      "projectedWinner": "Brazil",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Raphinha (8)",
      "projectedPichichiName": "Raphinha",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Jordi Ollé",
      "displayName": "Jordi O.",
      "rank": 25,
      "winPct": 0.562,
      "top3Pct": 2.704,
      "lastPct": 0.0,
      "avgPoints": 834.8,
      "maxPoints": 1205,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 8.26,
      "sdGallifantes": 61.33,
      "ceGallifantes": 0.28,
      "ceRank": 29,
      "winDeltaPp": 0.001,
      "top3DeltaPp": 0.228,
      "rankDelta": 5,
      "aliases": [
        "Jordi O"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Oriol Valls",
      "displayName": "Oriol V.",
      "rank": 26,
      "winPct": 0.524,
      "top3Pct": 2.088,
      "lastPct": 0.028,
      "avgPoints": 818.6,
      "maxPoints": 1200,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 1.31,
      "expectedGallifantes": 7.1,
      "sdGallifantes": 58.44,
      "ceGallifantes": 0.24,
      "ceRank": 37,
      "winDeltaPp": 0.17,
      "top3DeltaPp": 0.649,
      "rankDelta": 12,
      "aliases": [
        "Oriol V"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichi": "Harry Kane (7)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Isra",
      "displayName": "Isra",
      "rank": 27,
      "winPct": 0.521,
      "top3Pct": 2.306,
      "lastPct": 0.002,
      "avgPoints": 831.9,
      "maxPoints": 1193,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 19.874,
      "pichichiExpPoints": 5.87,
      "expectedGallifantes": 7.41,
      "sdGallifantes": 58.63,
      "ceGallifantes": 0.26,
      "ceRank": 34,
      "winDeltaPp": -0.017,
      "top3DeltaPp": -0.138,
      "rankDelta": 4,
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (9)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 9
    },
    {
      "player": "Pau",
      "displayName": "Pau",
      "rank": 28,
      "winPct": 0.513,
      "top3Pct": 3.188,
      "lastPct": 0.0,
      "avgPoints": 840.3,
      "maxPoints": 1218,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 8.68,
      "sdGallifantes": 60.25,
      "ceGallifantes": 0.3,
      "ceRank": 27,
      "winDeltaPp": -0.529,
      "top3DeltaPp": -2.006,
      "rankDelta": -2,
      "projectedWinner": "France",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Oriol Oltra",
      "displayName": "Oriol O.",
      "rank": 29,
      "winPct": 0.487,
      "top3Pct": 2.525,
      "lastPct": 0.0,
      "avgPoints": 836.0,
      "maxPoints": 1250,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 7.58,
      "sdGallifantes": 57.7,
      "ceGallifantes": 0.27,
      "ceRank": 31,
      "winDeltaPp": 0.019,
      "top3DeltaPp": 0.051,
      "rankDelta": 6,
      "aliases": [
        "Oriol O"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Paco",
      "displayName": "Paco",
      "rank": 30,
      "winPct": 0.484,
      "top3Pct": 1.405,
      "lastPct": 2.099,
      "avgPoints": 780.3,
      "maxPoints": 1149,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 5.92,
      "sdGallifantes": 54.86,
      "ceGallifantes": 0.22,
      "ceRank": 39,
      "winDeltaPp": -0.2,
      "top3DeltaPp": -0.599,
      "rankDelta": -1,
      "projectedWinner": "Argentina",
      "projectedFinalist": "France",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Jordi Cunyao",
      "displayName": "Jordi C.",
      "rank": 31,
      "winPct": 0.456,
      "top3Pct": 1.576,
      "lastPct": 3.433,
      "avgPoints": 780.6,
      "maxPoints": 1120,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 6.35,
      "sdGallifantes": 54.12,
      "ceGallifantes": 0.28,
      "ceRank": 30,
      "winDeltaPp": -0.31,
      "top3DeltaPp": -1.155,
      "rankDelta": -3,
      "aliases": [
        "Jordi C"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Brazil",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Martina",
      "displayName": "Martina",
      "rank": 32,
      "winPct": 0.437,
      "top3Pct": 2.263,
      "lastPct": 0.008,
      "avgPoints": 831.0,
      "maxPoints": 1232,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 6.79,
      "sdGallifantes": 54.53,
      "ceGallifantes": 0.25,
      "ceRank": 35,
      "winDeltaPp": -1.139,
      "top3DeltaPp": -4.439,
      "rankDelta": -14,
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Albert Cosí",
      "displayName": "Albert C.",
      "rank": 33,
      "winPct": 0.417,
      "top3Pct": 1.147,
      "lastPct": 15.34,
      "avgPoints": 736.7,
      "maxPoints": 1081,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 1.31,
      "expectedGallifantes": 7.63,
      "sdGallifantes": 51.07,
      "ceGallifantes": 0.75,
      "ceRank": 16,
      "winDeltaPp": -0.11,
      "top3DeltaPp": -0.423,
      "rankDelta": -1,
      "aliases": [
        "Albert C"
      ],
      "projectedWinner": "Argentina",
      "projectedFinalist": "Netherlands",
      "projectedPichichi": "Harry Kane (7)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Marc",
      "displayName": "Marc",
      "rank": 34,
      "winPct": 0.387,
      "top3Pct": 1.855,
      "lastPct": 0.006,
      "avgPoints": 827.9,
      "maxPoints": 1185,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 0.03,
      "expectedGallifantes": 5.87,
      "sdGallifantes": 50.91,
      "ceGallifantes": 0.23,
      "ceRank": 38,
      "winDeltaPp": 0.248,
      "top3DeltaPp": 1.019,
      "rankDelta": 11,
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Julián Álvarez (7)",
      "projectedPichichiName": "Julián Álvarez",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Daniela",
      "displayName": "Daniela",
      "rank": 35,
      "winPct": 0.383,
      "top3Pct": 1.401,
      "lastPct": 0.155,
      "avgPoints": 808.1,
      "maxPoints": 1218,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 5.18,
      "sdGallifantes": 49.82,
      "ceGallifantes": 0.19,
      "ceRank": 41,
      "winDeltaPp": -0.018,
      "top3DeltaPp": 0.054,
      "rankDelta": 2,
      "projectedWinner": "Spain",
      "projectedFinalist": "Brazil",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Biel",
      "displayName": "Biel",
      "rank": 36,
      "winPct": 0.374,
      "top3Pct": 1.43,
      "lastPct": 1.563,
      "avgPoints": 774.9,
      "maxPoints": 1166,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 5.19,
      "sdGallifantes": 49.52,
      "ceGallifantes": 0.19,
      "ceRank": 42,
      "winDeltaPp": -0.098,
      "top3DeltaPp": -0.247,
      "rankDelta": -2,
      "projectedWinner": "France",
      "projectedFinalist": "Norway",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Michael",
      "displayName": "Michael",
      "rank": 37,
      "winPct": 0.316,
      "top3Pct": 2.287,
      "lastPct": 0.005,
      "avgPoints": 829.3,
      "maxPoints": 1227,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 3.89,
      "expectedGallifantes": 6.0,
      "sdGallifantes": 48.14,
      "ceGallifantes": 0.24,
      "ceRank": 36,
      "winDeltaPp": -0.121,
      "top3DeltaPp": -0.703,
      "rankDelta": -1,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (6)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Teo",
      "displayName": "Teo",
      "rank": 38,
      "winPct": 0.281,
      "top3Pct": 1.57,
      "lastPct": 0.009,
      "avgPoints": 830.0,
      "maxPoints": 1183,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 3.92,
      "expectedGallifantes": 4.75,
      "sdGallifantes": 44.11,
      "ceGallifantes": 0.21,
      "ceRank": 40,
      "winDeltaPp": -0.017,
      "top3DeltaPp": -0.018,
      "rankDelta": 1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (7)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Manel Pujol",
      "displayName": "Manel P.",
      "rank": 39,
      "winPct": 0.25,
      "top3Pct": 0.895,
      "lastPct": 4.899,
      "avgPoints": 762.9,
      "maxPoints": 1123,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 4.15,
      "sdGallifantes": 40.25,
      "ceGallifantes": 0.27,
      "ceRank": 32,
      "winDeltaPp": -0.544,
      "top3DeltaPp": -1.549,
      "rankDelta": -12,
      "aliases": [
        "Manel P"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Brazil",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Xavi Ferrés",
      "displayName": "Xavi F.",
      "rank": 40,
      "winPct": 0.24,
      "top3Pct": 0.985,
      "lastPct": 0.111,
      "avgPoints": 799.0,
      "maxPoints": 1132,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 3.43,
      "sdGallifantes": 39.61,
      "ceGallifantes": 0.14,
      "ceRank": 46,
      "winDeltaPp": -1.088,
      "top3DeltaPp": -3.193,
      "rankDelta": -19,
      "aliases": [
        "Xavi F"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Albert Esteve",
      "displayName": "Albert E.",
      "rank": 41,
      "winPct": 0.231,
      "top3Pct": 1.025,
      "lastPct": 0.651,
      "avgPoints": 782.2,
      "maxPoints": 1152,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 0.03,
      "expectedGallifantes": 3.46,
      "sdGallifantes": 39.36,
      "ceGallifantes": 0.13,
      "ceRank": 48,
      "winDeltaPp": 0.0,
      "top3DeltaPp": 0.01,
      "rankDelta": 1,
      "aliases": [
        "Albert E"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "Netherlands",
      "projectedPichichi": "Gonçalo Ramos (7)",
      "projectedPichichiName": "Gonçalo Ramos",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Rafa Angulo",
      "displayName": "Rafa A.",
      "rank": 42,
      "winPct": 0.2,
      "top3Pct": 0.872,
      "lastPct": 0.36,
      "avgPoints": 793.1,
      "maxPoints": 1187,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 0.03,
      "expectedGallifantes": 3.05,
      "sdGallifantes": 36.48,
      "ceGallifantes": 0.14,
      "ceRank": 47,
      "winDeltaPp": -0.032,
      "top3DeltaPp": -0.376,
      "rankDelta": -1,
      "aliases": [
        "Rafa A"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Lamine Yamal (7)",
      "projectedPichichiName": "Lamine Yamal",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Manu GS",
      "displayName": "Manu G.",
      "rank": 43,
      "winPct": 0.158,
      "top3Pct": 0.629,
      "lastPct": 0.204,
      "avgPoints": 786.5,
      "maxPoints": 1157,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.28,
      "expectedGallifantes": 2.29,
      "sdGallifantes": 32.08,
      "ceGallifantes": 0.1,
      "ceRank": 52,
      "winDeltaPp": 0.064,
      "top3DeltaPp": 0.142,
      "rankDelta": 5,
      "aliases": [
        "Manu G"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Harry Kane (6)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 6
    },
    {
      "player": "David Muñoz",
      "displayName": "David M.",
      "rank": 44,
      "winPct": 0.117,
      "top3Pct": 0.839,
      "lastPct": 0.007,
      "avgPoints": 814.6,
      "maxPoints": 1171,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 3.83,
      "expectedGallifantes": 2.55,
      "sdGallifantes": 29.36,
      "ceGallifantes": 0.16,
      "ceRank": 45,
      "winDeltaPp": 0.081,
      "top3DeltaPp": 0.418,
      "rankDelta": 8,
      "aliases": [
        "David M"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichi": "Harry Kane (8)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Guillem Ochoa",
      "displayName": "Guillem O.",
      "rank": 45,
      "winPct": 0.09,
      "top3Pct": 0.615,
      "lastPct": 0.06,
      "avgPoints": 806.7,
      "maxPoints": 1236,
      "pichichiPlayerPct": 7.155,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.07,
      "expectedGallifantes": 2.0,
      "sdGallifantes": 25.85,
      "ceGallifantes": 0.13,
      "ceRank": 49,
      "winDeltaPp": -0.161,
      "top3DeltaPp": -0.696,
      "rankDelta": -5,
      "aliases": [
        "Guillem O"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Oyarzábal (6)",
      "projectedPichichiName": "Oyarzábal",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Toni Campanyà",
      "displayName": "Toni C.",
      "rank": 46,
      "winPct": 0.087,
      "top3Pct": 0.333,
      "lastPct": 3.535,
      "avgPoints": 758.9,
      "maxPoints": 1054,
      "pichichiPlayerPct": 9.308,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 3.94,
      "expectedGallifantes": 1.94,
      "sdGallifantes": 24.06,
      "ceGallifantes": 0.17,
      "ceRank": 43,
      "winDeltaPp": -0.011,
      "top3DeltaPp": -0.061,
      "rankDelta": 1,
      "aliases": [
        "Toni C"
      ],
      "projectedWinner": "Brazil",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Haaland (8)",
      "projectedPichichiName": "Haaland",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Jordi Reig",
      "displayName": "Jordi Re.",
      "rank": 47,
      "winPct": 0.071,
      "top3Pct": 0.456,
      "lastPct": 0.154,
      "avgPoints": 790.8,
      "maxPoints": 1202,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 1.31,
      "expectedGallifantes": 1.55,
      "sdGallifantes": 22.9,
      "ceGallifantes": 0.1,
      "ceRank": 53,
      "winDeltaPp": 0.023,
      "top3DeltaPp": 0.119,
      "rankDelta": 4,
      "aliases": [
        "Jordi Re",
        "Jordi Re."
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichi": "Harry Kane (7)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Norber",
      "displayName": "Norber",
      "rank": 48,
      "winPct": 0.07,
      "top3Pct": 0.335,
      "lastPct": 0.876,
      "avgPoints": 774.8,
      "maxPoints": 1140,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 3.83,
      "expectedGallifantes": 1.37,
      "sdGallifantes": 21.91,
      "ceGallifantes": 0.09,
      "ceRank": 54,
      "winDeltaPp": -0.047,
      "top3DeltaPp": -0.2,
      "rankDelta": -2,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Harry Kane (8)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Eduard Verdaguer",
      "displayName": "Eduard V.",
      "rank": 49,
      "winPct": 0.066,
      "top3Pct": 0.488,
      "lastPct": 6.29,
      "avgPoints": 756.6,
      "maxPoints": 1115,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.28,
      "expectedGallifantes": 2.65,
      "sdGallifantes": 23.03,
      "ceGallifantes": 0.29,
      "ceRank": 28,
      "winDeltaPp": -0.112,
      "top3DeltaPp": -0.359,
      "rankDelta": -6,
      "aliases": [
        "Eduard V"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "England",
      "projectedPichichi": "Harry Kane (6)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Enrique Moral",
      "displayName": "Enrique M.",
      "rank": 50,
      "winPct": 0.029,
      "top3Pct": 0.243,
      "lastPct": 20.345,
      "avgPoints": 719.4,
      "maxPoints": 1053,
      "pichichiPlayerPct": 8.526,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.28,
      "expectedGallifantes": 4.72,
      "sdGallifantes": 17.1,
      "ceGallifantes": 0.92,
      "ceRank": 13,
      "winDeltaPp": -0.045,
      "top3DeltaPp": -0.191,
      "rankDelta": 0,
      "aliases": [
        "Enrique M"
      ],
      "projectedWinner": "Germany",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Harry Kane (5)",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 5
    },
    {
      "player": "Jaume Martí",
      "displayName": "Jaume M.",
      "rank": 51,
      "winPct": 0.017,
      "top3Pct": 0.16,
      "lastPct": 0.374,
      "avgPoints": 780.0,
      "maxPoints": 1114,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.327,
      "pichichiExpPoints": 0.03,
      "expectedGallifantes": 0.72,
      "sdGallifantes": 11.76,
      "ceGallifantes": 0.08,
      "ceRank": 57,
      "winDeltaPp": -0.057,
      "top3DeltaPp": -0.3,
      "rankDelta": -2,
      "aliases": [
        "Jaume M"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "France",
      "projectedPichichi": "Olise (7)",
      "projectedPichichiName": "Olise",
      "projectedPichichiGoals": 7
    },
    {
      "player": "Nick",
      "displayName": "Nick",
      "rank": 52,
      "winPct": 0.011,
      "top3Pct": 0.101,
      "lastPct": 2.528,
      "avgPoints": 759.6,
      "maxPoints": 1122,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 0.89,
      "sdGallifantes": 10.03,
      "ceGallifantes": 0.12,
      "ceRank": 50,
      "winDeltaPp": -0.146,
      "top3DeltaPp": -0.492,
      "rankDelta": -8,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Ferran Torres (6)",
      "projectedPichichiName": "Ferran Torres",
      "projectedPichichiGoals": 6
    },
    {
      "player": "Eduardo Morales",
      "displayName": "Eduardo M.",
      "rank": 53,
      "winPct": 0.006,
      "top3Pct": 0.161,
      "lastPct": 0.347,
      "avgPoints": 785.1,
      "maxPoints": 1140,
      "pichichiPlayerPct": 12.343,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.85,
      "expectedGallifantes": 0.62,
      "sdGallifantes": 8.23,
      "ceGallifantes": 0.08,
      "ceRank": 56,
      "winDeltaPp": 0.002,
      "top3DeltaPp": 0.032,
      "rankDelta": 3,
      "aliases": [
        "Eduardo M"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "Spain",
      "projectedPichichi": "Vinicius (5)",
      "projectedPichichiName": "Vinicius",
      "projectedPichichiGoals": 5
    },
    {
      "player": "Andreu",
      "displayName": "Andreu",
      "rank": 54,
      "winPct": 0.004,
      "top3Pct": 0.029,
      "lastPct": 3.443,
      "avgPoints": 761.3,
      "maxPoints": 1103,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 2.55,
      "expectedGallifantes": 0.98,
      "sdGallifantes": 6.98,
      "ceGallifantes": 0.16,
      "ceRank": 44,
      "winDeltaPp": 0.0,
      "top3DeltaPp": -0.041,
      "rankDelta": 1,
      "projectedWinner": "France",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Dembélé (8)",
      "projectedPichichiName": "Dembélé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Pere",
      "displayName": "Pere",
      "rank": 55,
      "winPct": 0.003,
      "top3Pct": 0.048,
      "lastPct": 0.293,
      "avgPoints": 788.9,
      "maxPoints": 1139,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 3.89,
      "expectedGallifantes": 0.54,
      "sdGallifantes": 6.13,
      "ceGallifantes": 0.08,
      "ceRank": 55,
      "winDeltaPp": -0.01,
      "top3DeltaPp": -0.115,
      "rankDelta": -1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichi": "Mbappé (13)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 13
    },
    {
      "player": "Gerard",
      "displayName": "Gerard",
      "rank": 56,
      "winPct": 0.002,
      "top3Pct": 0.021,
      "lastPct": 2.11,
      "avgPoints": 761.9,
      "maxPoints": 1094,
      "pichichiPlayerPct": 25.917,
      "pichichiGoalsPct": 25.488,
      "pichichiExpPoints": 6.44,
      "expectedGallifantes": 0.64,
      "sdGallifantes": 5.2,
      "ceGallifantes": 0.1,
      "ceRank": 51,
      "winDeltaPp": -0.017,
      "top3DeltaPp": -0.076,
      "rankDelta": -3,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichi": "Mbappé (8)",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8
    },
    {
      "player": "Albert Benach",
      "displayName": "Albert B.",
      "rank": 57,
      "winPct": 0.0,
      "top3Pct": 0.001,
      "lastPct": 29.411,
      "avgPoints": 703.0,
      "maxPoints": 1033,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 5.91,
      "sdGallifantes": 9.08,
      "ceGallifantes": 1.48,
      "ceRank": 5,
      "winDeltaPp": -0.002,
      "top3DeltaPp": -0.007,
      "rankDelta": 0,
      "aliases": [
        "Albert B"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "France",
      "projectedPichichi": "Dembélé (5)",
      "projectedPichichiName": "Dembélé",
      "projectedPichichiGoals": 5
    }
  ],
  "pichichi": {
    "asOf": "26 Jun 2026, after Paraguay 0-0 Australia (60 matches played; end of 25 Jun games)",
    "source": "Manual update from confirmed scorer reports through 25 Jun 2026 matches M55-M60; pichichi proxy inputs updated after Group D/E/F completion.",
    "method": "current_goals_plus_future_team_matches",
    "playerBonusPoints": 15,
    "goalTotalBonusPoints": 10,
    "goalTotalDistribution": [
      {
        "goals": 7,
        "pct": 0.327
      },
      {
        "goals": 8,
        "pct": 25.488
      },
      {
        "goals": 9,
        "pct": 19.874
      },
      {
        "goals": 10,
        "pct": 23.624
      },
      {
        "goals": 11,
        "pct": 30.687
      }
    ],
    "trackedPlayers": [
      {
        "player": "Lionel Messi",
        "team": "Argentina",
        "currentGoals": 5,
        "topPct": 51.577,
        "tieSplitTopPct": 43.148
      },
      {
        "player": "Kylian Mbappé",
        "team": "France",
        "currentGoals": 4,
        "topPct": 25.917,
        "tieSplitTopPct": 20.819
      },
      {
        "player": "Vinícius Júnior",
        "team": "Brazil",
        "currentGoals": 4,
        "topPct": 12.343,
        "tieSplitTopPct": 10.855
      },
      {
        "player": "Erling Haaland",
        "team": "Norway",
        "currentGoals": 4,
        "topPct": 9.308,
        "tieSplitTopPct": 5.757
      },
      {
        "player": "Harry Kane",
        "team": "England",
        "currentGoals": 2,
        "topPct": 8.526,
        "tieSplitTopPct": 2.775
      },
      {
        "player": "Mikel Oyarzabal",
        "team": "Spain",
        "currentGoals": 2,
        "topPct": 7.155,
        "tieSplitTopPct": 2.537
      },
      {
        "player": "Brian Brobbey",
        "team": "Netherlands",
        "currentGoals": 3,
        "topPct": 7.105,
        "tieSplitTopPct": 2.602
      },
      {
        "player": "Deniz Undav",
        "team": "Germany",
        "currentGoals": 3,
        "topPct": 6.989,
        "tieSplitTopPct": 2.859
      },
      {
        "player": "Cristiano Ronaldo",
        "team": "Portugal",
        "currentGoals": 2,
        "topPct": 6.075,
        "tieSplitTopPct": 2.059
      },
      {
        "player": "Daniel Muñoz",
        "team": "Colombia",
        "currentGoals": 2,
        "topPct": 4.439,
        "tieSplitTopPct": 1.467
      },
      {
        "player": "Ismael Saibari",
        "team": "Morocco",
        "currentGoals": 3,
        "topPct": 4.267,
        "tieSplitTopPct": 1.571
      },
      {
        "player": "Johan Manzambi",
        "team": "Switzerland",
        "currentGoals": 3,
        "topPct": 3.4,
        "tieSplitTopPct": 1.138
      },
      {
        "player": "Maxi Araújo",
        "team": "Uruguay",
        "currentGoals": 2,
        "topPct": 2.663,
        "tieSplitTopPct": 0.923
      },
      {
        "player": "Jonathan David",
        "team": "Canada",
        "currentGoals": 3,
        "topPct": 2.317,
        "tieSplitTopPct": 0.857
      },
      {
        "player": "Ismaïla Sarr",
        "team": "Senegal",
        "currentGoals": 2,
        "topPct": 0.951,
        "tieSplitTopPct": 0.319
      },
      {
        "player": "Elijah Just",
        "team": "New Zealand",
        "currentGoals": 2,
        "topPct": 0.297,
        "tieSplitTopPct": 0.092
      },
      {
        "player": "Folarin Balogun",
        "team": "USA",
        "currentGoals": 2,
        "topPct": 0.098,
        "tieSplitTopPct": 0.019
      },
      {
        "player": "Ayase Ueda",
        "team": "Japan",
        "currentGoals": 2,
        "topPct": 0.082,
        "tieSplitTopPct": 0.013
      },
      {
        "player": "Daichi Kamada",
        "team": "Japan",
        "currentGoals": 2,
        "topPct": 0.082,
        "tieSplitTopPct": 0.013
      },
      {
        "player": "Ante Budimir",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 0.081,
        "tieSplitTopPct": 0.011
      },
      {
        "player": "Martin Baturina",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 0.081,
        "tieSplitTopPct": 0.011
      },
      {
        "player": "Petar Musa",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 0.081,
        "tieSplitTopPct": 0.011
      },
      {
        "player": "Julián Quiñones",
        "team": "Mexico",
        "currentGoals": 2,
        "topPct": 0.075,
        "tieSplitTopPct": 0.013
      },
      {
        "player": "Emam Ashour",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.064,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Mohamed Salah",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.064,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Mostafa Zico",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.064,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Trézéguet",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.064,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Nicolas Pépé",
        "team": "Côte d'Ivoire",
        "currentGoals": 2,
        "topPct": 0.063,
        "tieSplitTopPct": 0.013
      },
      {
        "player": "Anthony Elanga",
        "team": "Sweden",
        "currentGoals": 2,
        "topPct": 0.061,
        "tieSplitTopPct": 0.009
      },
      {
        "player": "Yasin Ayari",
        "team": "Sweden",
        "currentGoals": 2,
        "topPct": 0.061,
        "tieSplitTopPct": 0.009
      },
      {
        "player": "Marko Arnautović",
        "team": "Austria",
        "currentGoals": 1,
        "topPct": 0.051,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Romano Schmid",
        "team": "Austria",
        "currentGoals": 1,
        "topPct": 0.051,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Mohammad Mohebi",
        "team": "IR Iran",
        "currentGoals": 1,
        "topPct": 0.05,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Ramin Rezaeian",
        "team": "IR Iran",
        "currentGoals": 1,
        "topPct": 0.05,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Ermin Mahmić",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 2,
        "topPct": 0.045,
        "tieSplitTopPct": 0.008
      },
      {
        "player": "Abdulelah Al-Amri",
        "team": "Saudi Arabia",
        "currentGoals": 1,
        "topPct": 0.041,
        "tieSplitTopPct": 0.007
      },
      {
        "player": "Caleb Yirenkyi",
        "team": "Ghana",
        "currentGoals": 1,
        "topPct": 0.039,
        "tieSplitTopPct": 0.007
      },
      {
        "player": "Amine Gouiri",
        "team": "Algeria",
        "currentGoals": 1,
        "topPct": 0.028,
        "tieSplitTopPct": 0.004
      },
      {
        "player": "Nadhir Benbouali",
        "team": "Algeria",
        "currentGoals": 1,
        "topPct": 0.028,
        "tieSplitTopPct": 0.004
      },
      {
        "player": "Hélio Varela",
        "team": "Cabo Verde",
        "currentGoals": 1,
        "topPct": 0.025,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Kevin Pina",
        "team": "Cabo Verde",
        "currentGoals": 1,
        "topPct": 0.025,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Yoane Wissa",
        "team": "DR Congo",
        "currentGoals": 1,
        "topPct": 0.007,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Ali Iyad Olwan",
        "team": "Jordan",
        "currentGoals": 1,
        "topPct": 0.004,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Nizar Al-Rashdan",
        "team": "Jordan",
        "currentGoals": 1,
        "topPct": 0.004,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Ayman Hussein",
        "team": "Iraq",
        "currentGoals": 1,
        "topPct": 0.002,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Abbosbek Fayzullayev",
        "team": "Uzbekistan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Achraf Hakimi",
        "team": "Morocco",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Agustín Canobbio",
        "team": "Uruguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alex Freeman",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alexander Isak",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Amad Diallo",
        "team": "Côte d'Ivoire",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Arda Güler",
        "team": "Türkiye",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Auston Trusty",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Barış Alper Yılmaz",
        "team": "Türkiye",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Boualem Khoukhi",
        "team": "Qatar",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Bradley Barcola",
        "team": "France",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Breel Embolo",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Cody Gakpo",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Connor Metcalfe",
        "team": "Australia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Crysencio Summerville",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Cyle Larin",
        "team": "Canada",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Daizen Maeda",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Felix Nmecha",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ferran Torres",
        "team": "Spain",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Finn Surman",
        "team": "New Zealand",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Franck Kessié",
        "team": "Côte d'Ivoire",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gessime Yassine",
        "team": "Morocco",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gio Reyna",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gonzalo Plata",
        "team": "Ecuador",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gonçalo Ramos",
        "team": "Portugal",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Granit Xhaka",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hassan Al-Haydos",
        "team": "Qatar",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hazem Mastouri",
        "team": "Tunisia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hwang In-beom",
        "team": "Korea Republic",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ibrahim Mbaye",
        "team": "Senegal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jamal Musiala",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jaminton Campaz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jan Paul van Hecke",
        "team": "Netherlands",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "John McGinn",
        "team": "Scotland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jovo Lukić",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "João Neves",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jude Bellingham",
        "team": "England",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Julián Álvarez",
        "team": "Argentina",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Junya Itō",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kaan Ayhan",
        "team": "Türkiye",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kai Havertz",
        "team": "Germany",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Keito Nakamura",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kerim Alajbegovic",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ladislav Krejčí",
        "team": "Czechia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Lamine Yamal",
        "team": "Spain",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Leo Østigård",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Leroy Sané",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Livano Comenencia",
        "team": "Curaçao",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Luis Díaz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Luis Romo",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Marcus Pedersen",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Marcus Rashford",
        "team": "England",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mateo Chávez",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Matheus Cunha",
        "team": "Brazil",
        "currentGoals": 3,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mattias Svanberg",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Matías Galarza",
        "team": "Paraguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mauricio",
        "team": "Paraguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Michael Olise",
        "team": "France",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Michal Sadílek",
        "team": "Czechia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nathan Saliba",
        "team": "Canada",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nathaniel Brown",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nestory Irankunda",
        "team": "Australia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nico Schlotterbeck",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nilson Angulo",
        "team": "Ecuador",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nuno Mendes",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Oh Hyun-gyu",
        "team": "Korea Republic",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Omar Rekik",
        "team": "Tunisia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ousmane Dembélé",
        "team": "France",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Promise David",
        "team": "Canada",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Rafael Leão",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Raphinha",
        "team": "Brazil",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Raúl Jiménez",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ruben Vargas",
        "team": "Switzerland",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Sebastian Berhalter",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Soufiane Rahimi",
        "team": "Morocco",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Thapelo Maseko",
        "team": "South Africa",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Viktor Gyökeres",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Virgil van Dijk",
        "team": "Netherlands",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Wilson Isidor",
        "team": "Haiti",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Álvaro Fidalgo",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      }
    ],
    "missingParticipantPicks": []
  },
  "gallifantesPrizeSchedule": {
    "1": 750,
    "2": 250,
    "3": 100,
    "27": 20,
    "last": 20
  },
  "gallifantesSourceNote": "Computed directly from this 100,000-simulation distribution; ties split prizes for positions 1, 2, 3, 27, and last.",
  "lastPlaceNote": "lastPct is tie-split probability of finishing in the final position; ties for last split the last-place probability share.",
  "modelDetails": {
    "scoreModel": "empirical_recent_weighted_world_cup_scorelines",
    "recencyHalfLifeYears": 16.0,
    "baseYear": 2022,
    "source": "DataHub football/worldcup matches.csv sourced from Fjelstul World Cup Database; men only, 1930-2022",
    "groupDrawRatePct": 23.742,
    "knockoutDrawRatePct": 21.683
  },
  "deltaBaseline": "After M54 / end of June 24 games · 100,000 simulations",
  "deltaFields": [
    "winDeltaPp",
    "top3DeltaPp",
    "rankDelta"
  ],
  "oddsTableFields": [
    "rank",
    "displayName",
    "winPct",
    "winDeltaPp",
    "top3Pct",
    "lastPct",
    "expectedGallifantes",
    "projectedWinner",
    "projectedFinalist",
    "projectedPichichi"
  ],
  "oddsTableNote": "Website odds tab shows last-place probability before expected gallifantes, and replaces SD/CE columns with participant projected winner, finalist, and Pichichi."
};
