window.PORRA_ODDS_LATEST = {
  "generatedAt": "2026-06-23T12:29:06Z",
  "label": "After Jordan 1-2 Algeria",
  "model": "Monte Carlo: current-WC-weighted group scorelines + historical knockout scorelines + FIFA-rating winner assignment + Pichichi proxy",
  "simulations": 100000,
  "baselineLabelForDelta": "After New Zealand 1-3 Egypt",
  "players": [
    {
      "player": "Joan",
      "displayName": "Joan",
      "rank": 1,
      "winPct": 10.454,
      "winDeltaPp": 1.079,
      "top3Pct": 21.54,
      "avgPoints": 803.6,
      "maxPoints": 1233,
      "expectedGallifantes": 99.18,
      "sdGallifantes": 230.65,
      "ceGallifantes": 2.75,
      "ceRank": 1,
      "pichichiPlayerPct": 48.004,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 7.2
    },
    {
      "player": "Rafa Bravo",
      "displayName": "Rafa B.",
      "rank": 2,
      "winPct": 8.652,
      "winDeltaPp": 3.076,
      "top3Pct": 21.493,
      "avgPoints": 820.9,
      "maxPoints": 1255,
      "expectedGallifantes": 88.28,
      "sdGallifantes": 213.39,
      "ceGallifantes": 2.6,
      "ceRank": 2,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Oriol Oltra",
      "displayName": "Oriol O.",
      "rank": 3,
      "winPct": 7.088,
      "winDeltaPp": 3.413,
      "top3Pct": 20.281,
      "avgPoints": 819.5,
      "maxPoints": 1202,
      "expectedGallifantes": 76.84,
      "sdGallifantes": 196.68,
      "ceGallifantes": 2.31,
      "ceRank": 3,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "JoanRa",
      "displayName": "JoanRa",
      "rank": 4,
      "winPct": 5.609,
      "winDeltaPp": 0.08,
      "top3Pct": 13.085,
      "avgPoints": 790.1,
      "maxPoints": 1180,
      "expectedGallifantes": 55.89,
      "sdGallifantes": 176.51,
      "ceGallifantes": 1.29,
      "ceRank": 6,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 1.71
    },
    {
      "player": "Aleix",
      "displayName": "Aleix",
      "rank": 5,
      "winPct": 5.493,
      "winDeltaPp": 2.926,
      "top3Pct": 17.041,
      "avgPoints": 819.2,
      "maxPoints": 1179,
      "expectedGallifantes": 61.93,
      "sdGallifantes": 176.56,
      "ceGallifantes": 1.73,
      "ceRank": 4,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 1.71
    },
    {
      "player": "Chús",
      "displayName": "Chús",
      "rank": 6,
      "winPct": 5.228,
      "winDeltaPp": -1.731,
      "top3Pct": 13.389,
      "avgPoints": 795.8,
      "maxPoints": 1167,
      "expectedGallifantes": 54.17,
      "sdGallifantes": 171.49,
      "ceGallifantes": 1.31,
      "ceRank": 5,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0
    },
    {
      "player": "Sergi Sanromà",
      "displayName": "Sergi S.",
      "rank": 7,
      "winPct": 3.461,
      "winDeltaPp": 1.333,
      "top3Pct": 10.606,
      "avgPoints": 798.1,
      "maxPoints": 1224,
      "expectedGallifantes": 38.83,
      "sdGallifantes": 142.98,
      "ceGallifantes": 0.95,
      "ceRank": 9,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Pablo",
      "displayName": "Pablo",
      "rank": 8,
      "winPct": 3.456,
      "winDeltaPp": -3.808,
      "top3Pct": 12.068,
      "avgPoints": 808.3,
      "maxPoints": 1220,
      "expectedGallifantes": 41.37,
      "sdGallifantes": 144.06,
      "ceGallifantes": 1.08,
      "ceRank": 7,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Bernat Garreta",
      "displayName": "Bernat G.",
      "rank": 9,
      "winPct": 3.256,
      "winDeltaPp": -1.439,
      "top3Pct": 7.25,
      "avgPoints": 756.2,
      "maxPoints": 1135,
      "expectedGallifantes": 32.06,
      "sdGallifantes": 136.89,
      "ceGallifantes": 0.65,
      "ceRank": 17,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.82
    },
    {
      "player": "Martina",
      "displayName": "Martina",
      "rank": 10,
      "winPct": 3.218,
      "winDeltaPp": -0.449,
      "top3Pct": 11.634,
      "avgPoints": 803.9,
      "maxPoints": 1218,
      "expectedGallifantes": 39.03,
      "sdGallifantes": 139.5,
      "ceGallifantes": 1.04,
      "ceRank": 8,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Oscar Campanyà",
      "displayName": "Oscar C.",
      "rank": 11,
      "winPct": 2.613,
      "winDeltaPp": 1.212,
      "top3Pct": 8.701,
      "avgPoints": 796.0,
      "maxPoints": 1204,
      "expectedGallifantes": 30.69,
      "sdGallifantes": 126.03,
      "ceGallifantes": 0.76,
      "ceRank": 13,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Rubi",
      "displayName": "Rubi",
      "rank": 12,
      "winPct": 2.417,
      "winDeltaPp": 0.378,
      "top3Pct": 7.324,
      "avgPoints": 785.5,
      "maxPoints": 1204,
      "expectedGallifantes": 27.19,
      "sdGallifantes": 120.72,
      "ceGallifantes": 0.64,
      "ceRank": 18,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Oriol Valls",
      "displayName": "Oriol V.",
      "rank": 13,
      "winPct": 2.402,
      "winDeltaPp": 0.757,
      "top3Pct": 7.581,
      "avgPoints": 788.7,
      "maxPoints": 1146,
      "expectedGallifantes": 27.51,
      "sdGallifantes": 120.67,
      "ceGallifantes": 0.66,
      "ceRank": 16,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 1.83
    },
    {
      "player": "Pol",
      "displayName": "Pol",
      "rank": 14,
      "winPct": 2.283,
      "winDeltaPp": 0.739,
      "top3Pct": 9.142,
      "avgPoints": 802.9,
      "maxPoints": 1154,
      "expectedGallifantes": 29.19,
      "sdGallifantes": 119.41,
      "ceGallifantes": 0.77,
      "ceRank": 12,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Emiliano",
      "displayName": "Emiliano",
      "rank": 15,
      "winPct": 2.116,
      "winDeltaPp": 1.017,
      "top3Pct": 8.377,
      "avgPoints": 799.2,
      "maxPoints": 1190,
      "expectedGallifantes": 26.92,
      "sdGallifantes": 115.13,
      "ceGallifantes": 0.71,
      "ceRank": 14,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Marc",
      "displayName": "Marc",
      "rank": 16,
      "winPct": 2.036,
      "winDeltaPp": -2.681,
      "top3Pct": 8.581,
      "avgPoints": 801.8,
      "maxPoints": 1184,
      "expectedGallifantes": 26.7,
      "sdGallifantes": 113.6,
      "ceGallifantes": 0.71,
      "ceRank": 15,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 0.01
    },
    {
      "player": "Andy",
      "displayName": "Andy",
      "rank": 17,
      "winPct": 1.877,
      "winDeltaPp": 0.324,
      "top3Pct": 4.805,
      "avgPoints": 775.2,
      "maxPoints": 1116,
      "expectedGallifantes": 19.69,
      "sdGallifantes": 105.79,
      "ceGallifantes": 0.44,
      "ceRank": 26,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Xavi Ferrés",
      "displayName": "Xavi F.",
      "rank": 18,
      "winPct": 1.845,
      "winDeltaPp": -0.451,
      "top3Pct": 5.854,
      "avgPoints": 778.4,
      "maxPoints": 1188,
      "expectedGallifantes": 21.25,
      "sdGallifantes": 106.36,
      "ceGallifantes": 0.51,
      "ceRank": 22,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Carlo",
      "displayName": "Carlo",
      "rank": 19,
      "winPct": 1.696,
      "winDeltaPp": 0.085,
      "top3Pct": 4.612,
      "avgPoints": 765.9,
      "maxPoints": 1135,
      "expectedGallifantes": 18.49,
      "sdGallifantes": 101.37,
      "ceGallifantes": 0.43,
      "ceRank": 28,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.82
    },
    {
      "player": "Pau",
      "displayName": "Pau",
      "rank": 20,
      "winPct": 1.642,
      "winDeltaPp": -0.003,
      "top3Pct": 6.666,
      "avgPoints": 794.6,
      "maxPoints": 1193,
      "expectedGallifantes": 21.26,
      "sdGallifantes": 102.18,
      "ceGallifantes": 0.57,
      "ceRank": 19,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Jaume Cardús",
      "displayName": "Jaume C.",
      "rank": 21,
      "winPct": 1.622,
      "winDeltaPp": -2.012,
      "top3Pct": 4.592,
      "avgPoints": 775.0,
      "maxPoints": 1140,
      "expectedGallifantes": 18.0,
      "sdGallifantes": 99.37,
      "ceGallifantes": 0.43,
      "ceRank": 27,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 1.71
    },
    {
      "player": "Nicolau",
      "displayName": "Nicolau",
      "rank": 22,
      "winPct": 1.434,
      "winDeltaPp": -0.129,
      "top3Pct": 3.338,
      "avgPoints": 738.5,
      "maxPoints": 1126,
      "expectedGallifantes": 14.67,
      "sdGallifantes": 92.41,
      "ceGallifantes": 0.33,
      "ceRank": 33,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0
    },
    {
      "player": "Antonio",
      "displayName": "Antonio",
      "rank": 23,
      "winPct": 1.429,
      "winDeltaPp": -1.644,
      "top3Pct": 4.987,
      "avgPoints": 752.1,
      "maxPoints": 1108,
      "expectedGallifantes": 17.71,
      "sdGallifantes": 95.15,
      "ceGallifantes": 0.45,
      "ceRank": 25,
      "pichichiPlayerPct": 7.366,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.1
    },
    {
      "player": "Miquel",
      "displayName": "Miquel",
      "rank": 24,
      "winPct": 1.319,
      "winDeltaPp": 0.003,
      "top3Pct": 5.344,
      "avgPoints": 790.3,
      "maxPoints": 1150,
      "expectedGallifantes": 17.19,
      "sdGallifantes": 91.93,
      "ceGallifantes": 0.46,
      "ceRank": 24,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 1.83
    },
    {
      "player": "Juanma",
      "displayName": "Juanma",
      "rank": 25,
      "winPct": 1.306,
      "winDeltaPp": 0.391,
      "top3Pct": 5.33,
      "avgPoints": 789.9,
      "maxPoints": 1149,
      "expectedGallifantes": 17.04,
      "sdGallifantes": 91.52,
      "ceGallifantes": 0.46,
      "ceRank": 23,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Bernat Raventós",
      "displayName": "Bernat R.",
      "rank": 26,
      "winPct": 1.227,
      "winDeltaPp": 0.577,
      "top3Pct": 4.396,
      "avgPoints": 777.6,
      "maxPoints": 1203,
      "expectedGallifantes": 15.03,
      "sdGallifantes": 87.83,
      "ceGallifantes": 0.39,
      "ceRank": 30,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Jordi Raventós",
      "displayName": "Jordi Ra.",
      "rank": 27,
      "winPct": 1.176,
      "winDeltaPp": -0.264,
      "top3Pct": 3.127,
      "avgPoints": 741.7,
      "maxPoints": 1106,
      "expectedGallifantes": 12.92,
      "sdGallifantes": 84.75,
      "ceGallifantes": 0.32,
      "ceRank": 35,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Toni Campanyà",
      "displayName": "Toni C.",
      "rank": 28,
      "winPct": 1.132,
      "winDeltaPp": 0.329,
      "top3Pct": 2.516,
      "avgPoints": 721.9,
      "maxPoints": 1050,
      "expectedGallifantes": 11.99,
      "sdGallifantes": 82.1,
      "ceGallifantes": 0.36,
      "ceRank": 31,
      "pichichiPlayerPct": 7.366,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 2.81
    },
    {
      "player": "Biel",
      "displayName": "Biel",
      "rank": 29,
      "winPct": 1.003,
      "winDeltaPp": -0.734,
      "top3Pct": 2.568,
      "avgPoints": 734.7,
      "maxPoints": 1107,
      "expectedGallifantes": 11.03,
      "sdGallifantes": 78.09,
      "ceGallifantes": 0.3,
      "ceRank": 38,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Eduard Verdaguer",
      "displayName": "Eduard V.",
      "rank": 30,
      "winPct": 0.973,
      "winDeltaPp": -0.975,
      "top3Pct": 2.944,
      "avgPoints": 733.2,
      "maxPoints": 1153,
      "expectedGallifantes": 11.51,
      "sdGallifantes": 77.67,
      "ceGallifantes": 0.34,
      "ceRank": 32,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.82
    },
    {
      "player": "Albert Cosí",
      "displayName": "Albert C.",
      "rank": 31,
      "winPct": 0.93,
      "winDeltaPp": 0.073,
      "top3Pct": 2.372,
      "avgPoints": 700.5,
      "maxPoints": 1076,
      "expectedGallifantes": 12.53,
      "sdGallifantes": 75.25,
      "ceGallifantes": 0.81,
      "ceRank": 11,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 1.83
    },
    {
      "player": "Gerard",
      "displayName": "Gerard",
      "rank": 32,
      "winPct": 0.873,
      "winDeltaPp": 0.06,
      "top3Pct": 3.532,
      "avgPoints": 771.3,
      "maxPoints": 1174,
      "expectedGallifantes": 11.54,
      "sdGallifantes": 75.31,
      "ceGallifantes": 0.32,
      "ceRank": 34,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Bernat Orriols",
      "displayName": "Bernat O.",
      "rank": 33,
      "winPct": 0.838,
      "winDeltaPp": 0.319,
      "top3Pct": 2.75,
      "avgPoints": 747.3,
      "maxPoints": 1111,
      "expectedGallifantes": 10.15,
      "sdGallifantes": 72.73,
      "ceGallifantes": 0.28,
      "ceRank": 39,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 3.65
    },
    {
      "player": "Guille Amor",
      "displayName": "Guille A.",
      "rank": 34,
      "winPct": 0.81,
      "winDeltaPp": 0.106,
      "top3Pct": 2.582,
      "avgPoints": 744.7,
      "maxPoints": 1129,
      "expectedGallifantes": 9.75,
      "sdGallifantes": 71.3,
      "ceGallifantes": 0.28,
      "ceRank": 40,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.82
    },
    {
      "player": "Teo",
      "displayName": "Teo",
      "rank": 35,
      "winPct": 0.719,
      "winDeltaPp": -0.0,
      "top3Pct": 3.229,
      "avgPoints": 783.6,
      "maxPoints": 1175,
      "expectedGallifantes": 10.04,
      "sdGallifantes": 68.84,
      "ceGallifantes": 0.31,
      "ceRank": 36,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Paco",
      "displayName": "Paco",
      "rank": 36,
      "winPct": 0.657,
      "winDeltaPp": -0.024,
      "top3Pct": 1.98,
      "avgPoints": 733.9,
      "maxPoints": 1115,
      "expectedGallifantes": 7.94,
      "sdGallifantes": 64.01,
      "ceGallifantes": 0.26,
      "ceRank": 41,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Oscar Bordas",
      "displayName": "Oscar B.",
      "rank": 37,
      "winPct": 0.636,
      "winDeltaPp": -0.161,
      "top3Pct": 3.242,
      "avgPoints": 788.7,
      "maxPoints": 1170,
      "expectedGallifantes": 9.5,
      "sdGallifantes": 65.6,
      "ceGallifantes": 0.3,
      "ceRank": 37,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Albert Esteve",
      "displayName": "Albert E.",
      "rank": 38,
      "winPct": 0.548,
      "winDeltaPp": -0.024,
      "top3Pct": 1.727,
      "avgPoints": 733.8,
      "maxPoints": 1133,
      "expectedGallifantes": 6.78,
      "sdGallifantes": 58.56,
      "ceGallifantes": 0.23,
      "ceRank": 43,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 0.01
    },
    {
      "player": "Nick",
      "displayName": "Nick",
      "rank": 39,
      "winPct": 0.54,
      "winDeltaPp": 0.401,
      "top3Pct": 1.799,
      "avgPoints": 742.4,
      "maxPoints": 1115,
      "expectedGallifantes": 6.71,
      "sdGallifantes": 58.44,
      "ceGallifantes": 0.21,
      "ceRank": 46,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0
    },
    {
      "player": "Michael",
      "displayName": "Michael",
      "rank": 40,
      "winPct": 0.497,
      "winDeltaPp": -0.587,
      "top3Pct": 2.51,
      "avgPoints": 769.8,
      "maxPoints": 1148,
      "expectedGallifantes": 7.5,
      "sdGallifantes": 57.99,
      "ceGallifantes": 0.26,
      "ceRank": 42,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 3.65
    },
    {
      "player": "Rafa Angulo",
      "displayName": "Rafa A.",
      "rank": 41,
      "winPct": 0.481,
      "winDeltaPp": -0.009,
      "top3Pct": 2.083,
      "avgPoints": 753.1,
      "maxPoints": 1102,
      "expectedGallifantes": 6.74,
      "sdGallifantes": 56.44,
      "ceGallifantes": 0.22,
      "ceRank": 45,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 0.01
    },
    {
      "player": "Daniela",
      "displayName": "Daniela",
      "rank": 42,
      "winPct": 0.446,
      "winDeltaPp": 0.175,
      "top3Pct": 1.624,
      "avgPoints": 760.5,
      "maxPoints": 1149,
      "expectedGallifantes": 5.85,
      "sdGallifantes": 53.47,
      "ceGallifantes": 0.21,
      "ceRank": 47,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Jordi Reig",
      "displayName": "Jordi Re.",
      "rank": 43,
      "winPct": 0.423,
      "winDeltaPp": -0.259,
      "top3Pct": 1.714,
      "avgPoints": 744.1,
      "maxPoints": 1134,
      "expectedGallifantes": 5.87,
      "sdGallifantes": 52.82,
      "ceGallifantes": 0.2,
      "ceRank": 49,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 1.83
    },
    {
      "player": "Manel Pujol",
      "displayName": "Manel P.",
      "rank": 44,
      "winPct": 0.406,
      "winDeltaPp": -0.616,
      "top3Pct": 1.262,
      "avgPoints": 706.1,
      "maxPoints": 1043,
      "expectedGallifantes": 6.77,
      "sdGallifantes": 50.74,
      "ceGallifantes": 0.53,
      "ceRank": 21,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 5.36
    },
    {
      "player": "Jaume Martí",
      "displayName": "Jaume M.",
      "rank": 45,
      "winPct": 0.401,
      "winDeltaPp": 0.113,
      "top3Pct": 1.655,
      "avgPoints": 743.0,
      "maxPoints": 1172,
      "expectedGallifantes": 5.69,
      "sdGallifantes": 51.49,
      "ceGallifantes": 0.2,
      "ceRank": 48,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 0.01
    },
    {
      "player": "Jordi Ollé",
      "displayName": "Jordi O.",
      "rank": 46,
      "winPct": 0.257,
      "winDeltaPp": -0.04,
      "top3Pct": 1.276,
      "avgPoints": 760.2,
      "maxPoints": 1119,
      "expectedGallifantes": 4.08,
      "sdGallifantes": 41.84,
      "ceGallifantes": 0.17,
      "ceRank": 50,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Enrique Moral",
      "displayName": "Enrique M.",
      "rank": 47,
      "winPct": 0.229,
      "winDeltaPp": -0.322,
      "top3Pct": 1.061,
      "avgPoints": 697.1,
      "maxPoints": 1082,
      "expectedGallifantes": 5.62,
      "sdGallifantes": 39.98,
      "ceGallifantes": 0.55,
      "ceRank": 20,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.82
    },
    {
      "player": "Jordi Cunyao",
      "displayName": "Jordi C.",
      "rank": 48,
      "winPct": 0.203,
      "winDeltaPp": 0.029,
      "top3Pct": 0.791,
      "avgPoints": 711.3,
      "maxPoints": 1087,
      "expectedGallifantes": 4.47,
      "sdGallifantes": 36.72,
      "ceGallifantes": 0.42,
      "ceRank": 29,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.084,
      "pichichiExpPoints": 3.66
    },
    {
      "player": "Isra",
      "displayName": "Isra",
      "rank": 49,
      "winPct": 0.173,
      "winDeltaPp": 0.023,
      "top3Pct": 0.919,
      "avgPoints": 756.4,
      "maxPoints": 1152,
      "expectedGallifantes": 3.05,
      "sdGallifantes": 34.71,
      "ceGallifantes": 0.16,
      "ceRank": 51,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 28.257,
      "pichichiExpPoints": 6.47
    },
    {
      "player": "Manu GS",
      "displayName": "Manu G.",
      "rank": 50,
      "winPct": 0.12,
      "winDeltaPp": -0.335,
      "top3Pct": 0.532,
      "avgPoints": 723.6,
      "maxPoints": 1090,
      "expectedGallifantes": 2.27,
      "sdGallifantes": 28.67,
      "ceGallifantes": 0.15,
      "ceRank": 53,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.82
    },
    {
      "player": "Norber",
      "displayName": "Norber",
      "rank": 51,
      "winPct": 0.096,
      "winDeltaPp": -0.105,
      "top3Pct": 0.428,
      "avgPoints": 718.1,
      "maxPoints": 1144,
      "expectedGallifantes": 2.44,
      "sdGallifantes": 25.81,
      "ceGallifantes": 0.23,
      "ceRank": 44,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 3.53
    },
    {
      "player": "Eduardo Morales",
      "displayName": "Eduardo M.",
      "rank": 52,
      "winPct": 0.069,
      "winDeltaPp": -0.039,
      "top3Pct": 0.498,
      "avgPoints": 739.7,
      "maxPoints": 1148,
      "expectedGallifantes": 1.73,
      "sdGallifantes": 22.37,
      "ceGallifantes": 0.14,
      "ceRank": 54,
      "pichichiPlayerPct": 5.511,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.83
    },
    {
      "player": "Andreu",
      "displayName": "Andreu",
      "rank": 53,
      "winPct": 0.061,
      "winDeltaPp": 0.007,
      "top3Pct": 0.313,
      "avgPoints": 725.6,
      "maxPoints": 1096,
      "expectedGallifantes": 1.59,
      "sdGallifantes": 20.62,
      "ceGallifantes": 0.15,
      "ceRank": 52,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 1.71
    },
    {
      "player": "Pere",
      "displayName": "Pere",
      "rank": 54,
      "winPct": 0.054,
      "winDeltaPp": -0.141,
      "top3Pct": 0.416,
      "avgPoints": 752.8,
      "maxPoints": 1149,
      "expectedGallifantes": 1.49,
      "sdGallifantes": 20.48,
      "ceGallifantes": 0.12,
      "ceRank": 55,
      "pichichiPlayerPct": 24.319,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 3.65
    },
    {
      "player": "Guillem Ochoa",
      "displayName": "Guillem O.",
      "rank": 55,
      "winPct": 0.044,
      "winDeltaPp": -0.002,
      "top3Pct": 0.268,
      "avgPoints": 738.7,
      "maxPoints": 1144,
      "expectedGallifantes": 1.17,
      "sdGallifantes": 17.92,
      "ceGallifantes": 0.11,
      "ceRank": 57,
      "pichichiPlayerPct": 5.26,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.79
    },
    {
      "player": "David Muñoz",
      "displayName": "David M.",
      "rank": 56,
      "winPct": 0.013,
      "winDeltaPp": -0.019,
      "top3Pct": 0.191,
      "avgPoints": 731.3,
      "maxPoints": 1078,
      "expectedGallifantes": 0.92,
      "sdGallifantes": 11.67,
      "ceGallifantes": 0.11,
      "ceRank": 56,
      "pichichiPlayerPct": 12.163,
      "pichichiGoalsPct": 17.078,
      "pichichiExpPoints": 3.53
    },
    {
      "player": "Albert Benach",
      "displayName": "Albert B.",
      "rank": 57,
      "winPct": 0.009,
      "winDeltaPp": -0.024,
      "top3Pct": 0.075,
      "avgPoints": 673.3,
      "maxPoints": 1017,
      "expectedGallifantes": 4.22,
      "sdGallifantes": 11.39,
      "ceGallifantes": 0.87,
      "ceRank": 10,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0
    }
  ],
  "pichichi": {
    "asOf": "23 Jun 2026, after Jordan 1-2 Algeria",
    "source": "Manual update from confirmed match reports through Jordan 1-2 Algeria; scorers added from public match reports.",
    "method": "current_goals_plus_future_team_matches",
    "playerBonusPoints": 15,
    "goalTotalBonusPoints": 10,
    "goalTotalDistribution": [
      {
        "goals": 7,
        "pct": 0.084
      },
      {
        "goals": 8,
        "pct": 17.078
      },
      {
        "goals": 9,
        "pct": 28.257
      },
      {
        "goals": 10,
        "pct": 23.607
      },
      {
        "goals": 11,
        "pct": 30.974
      }
    ],
    "trackedPlayers": [
      {
        "player": "Lionel Messi",
        "team": "Argentina",
        "currentGoals": 5,
        "topPct": 48.004,
        "tieSplitTopPct": 39.642
      },
      {
        "player": "Kylian Mbappé",
        "team": "France",
        "currentGoals": 4,
        "topPct": 24.319,
        "tieSplitTopPct": 19.93
      },
      {
        "player": "Harry Kane",
        "team": "England",
        "currentGoals": 2,
        "topPct": 12.163,
        "tieSplitTopPct": 8.984
      },
      {
        "player": "Deniz Undav",
        "team": "Germany",
        "currentGoals": 3,
        "topPct": 12.133,
        "tieSplitTopPct": 9.206
      },
      {
        "player": "Erling Haaland",
        "team": "Norway",
        "currentGoals": 4,
        "topPct": 7.366,
        "tieSplitTopPct": 5.021
      },
      {
        "player": "Matheus Cunha",
        "team": "Brazil",
        "currentGoals": 2,
        "topPct": 5.511,
        "tieSplitTopPct": 1.118
      },
      {
        "player": "Vinícius Júnior",
        "team": "Brazil",
        "currentGoals": 2,
        "topPct": 5.511,
        "tieSplitTopPct": 1.118
      },
      {
        "player": "Brian Brobbey",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 5.373,
        "tieSplitTopPct": 0.893
      },
      {
        "player": "Cody Gakpo",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 5.373,
        "tieSplitTopPct": 0.893
      },
      {
        "player": "Crysencio Summerville",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 5.373,
        "tieSplitTopPct": 0.893
      },
      {
        "player": "Mikel Oyarzabal",
        "team": "Spain",
        "currentGoals": 2,
        "topPct": 5.26,
        "tieSplitTopPct": 1.291
      },
      {
        "player": "Jonathan David",
        "team": "Canada",
        "currentGoals": 3,
        "topPct": 4.174,
        "tieSplitTopPct": 2.878
      },
      {
        "player": "Ismael Saibari",
        "team": "Morocco",
        "currentGoals": 2,
        "topPct": 4.052,
        "tieSplitTopPct": 1.027
      },
      {
        "player": "João Neves",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 3.571,
        "tieSplitTopPct": 0.838
      },
      {
        "player": "Daniel Muñoz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 3.114,
        "tieSplitTopPct": 0.482
      },
      {
        "player": "Jaminton Campaz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 3.114,
        "tieSplitTopPct": 0.482
      },
      {
        "player": "Luis Díaz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 3.114,
        "tieSplitTopPct": 0.482
      },
      {
        "player": "Johan Manzambi",
        "team": "Switzerland",
        "currentGoals": 2,
        "topPct": 2.917,
        "tieSplitTopPct": 0.717
      },
      {
        "player": "Ayase Ueda",
        "team": "Japan",
        "currentGoals": 2,
        "topPct": 2.892,
        "tieSplitTopPct": 0.557
      },
      {
        "player": "Daichi Kamada",
        "team": "Japan",
        "currentGoals": 2,
        "topPct": 2.892,
        "tieSplitTopPct": 0.557
      },
      {
        "player": "Folarin Balogun",
        "team": "USA",
        "currentGoals": 2,
        "topPct": 2.715,
        "tieSplitTopPct": 0.654
      },
      {
        "player": "Maxi Araújo",
        "team": "Uruguay",
        "currentGoals": 2,
        "topPct": 2.254,
        "tieSplitTopPct": 0.539
      },
      {
        "player": "Martin Baturina",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 1.705,
        "tieSplitTopPct": 0.312
      },
      {
        "player": "Petar Musa",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 1.705,
        "tieSplitTopPct": 0.312
      },
      {
        "player": "Yasin Ayari",
        "team": "Sweden",
        "currentGoals": 2,
        "topPct": 1.321,
        "tieSplitTopPct": 0.339
      },
      {
        "player": "Caleb Yirenkyi",
        "team": "Ghana",
        "currentGoals": 1,
        "topPct": 1.126,
        "tieSplitTopPct": 0.274
      },
      {
        "player": "Ismaïla Sarr",
        "team": "Senegal",
        "currentGoals": 2,
        "topPct": 0.871,
        "tieSplitTopPct": 0.212
      },
      {
        "player": "Yoane Wissa",
        "team": "DR Congo",
        "currentGoals": 1,
        "topPct": 0.574,
        "tieSplitTopPct": 0.137
      },
      {
        "player": "Abbosbek Fayzullayev",
        "team": "Uzbekistan",
        "currentGoals": 1,
        "topPct": 0.379,
        "tieSplitTopPct": 0.093
      },
      {
        "player": "Elijah Just",
        "team": "New Zealand",
        "currentGoals": 2,
        "topPct": 0.243,
        "tieSplitTopPct": 0.055
      },
      {
        "player": "Amad Diallo",
        "team": "Côte d'Ivoire",
        "currentGoals": 1,
        "topPct": 0.032,
        "tieSplitTopPct": 0.004
      },
      {
        "player": "Franck Kessié",
        "team": "Côte d'Ivoire",
        "currentGoals": 1,
        "topPct": 0.032,
        "tieSplitTopPct": 0.004
      },
      {
        "player": "Julián Quiñones",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.032,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Luis Romo",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.032,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Raúl Jiménez",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.032,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Hwang In-beom",
        "team": "Korea Republic",
        "currentGoals": 1,
        "topPct": 0.026,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Oh Hyun-gyu",
        "team": "Korea Republic",
        "currentGoals": 1,
        "topPct": 0.026,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Connor Metcalfe",
        "team": "Australia",
        "currentGoals": 1,
        "topPct": 0.025,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Nestory Irankunda",
        "team": "Australia",
        "currentGoals": 1,
        "topPct": 0.025,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Marko Arnautović",
        "team": "Austria",
        "currentGoals": 1,
        "topPct": 0.024,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Romano Schmid",
        "team": "Austria",
        "currentGoals": 1,
        "topPct": 0.024,
        "tieSplitTopPct": 0.003
      },
      {
        "player": "Emam Ashour",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.022,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Mohamed Salah",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.022,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Mostafa Zico",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.022,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Trézéguet",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.022,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Matías Galarza",
        "team": "Paraguay",
        "currentGoals": 1,
        "topPct": 0.017,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Mauricio",
        "team": "Paraguay",
        "currentGoals": 1,
        "topPct": 0.017,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "John McGinn",
        "team": "Scotland",
        "currentGoals": 1,
        "topPct": 0.016,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Ladislav Krejčí",
        "team": "Czechia",
        "currentGoals": 1,
        "topPct": 0.016,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Michal Sadílek",
        "team": "Czechia",
        "currentGoals": 1,
        "topPct": 0.016,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Mohammad Mohebi",
        "team": "IR Iran",
        "currentGoals": 1,
        "topPct": 0.016,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Ramin Rezaeian",
        "team": "IR Iran",
        "currentGoals": 1,
        "topPct": 0.016,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Abdulelah Al-Amri",
        "team": "Saudi Arabia",
        "currentGoals": 1,
        "topPct": 0.014,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Amine Gouiri",
        "team": "Algeria",
        "currentGoals": 1,
        "topPct": 0.014,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Nadhir Benbouali",
        "team": "Algeria",
        "currentGoals": 1,
        "topPct": 0.014,
        "tieSplitTopPct": 0.002
      },
      {
        "player": "Hélio Varela",
        "team": "Cabo Verde",
        "currentGoals": 1,
        "topPct": 0.01,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Kevin Pina",
        "team": "Cabo Verde",
        "currentGoals": 1,
        "topPct": 0.01,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Boualem Khoukhi",
        "team": "Qatar",
        "currentGoals": 1,
        "topPct": 0.007,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Ermin Mahmić",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 1,
        "topPct": 0.004,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jovo Lukić",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 1,
        "topPct": 0.004,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Livano Comenencia",
        "team": "Curaçao",
        "currentGoals": 1,
        "topPct": 0.004,
        "tieSplitTopPct": 0.001
      },
      {
        "player": "Ayman Hussein",
        "team": "Iraq",
        "currentGoals": 1,
        "topPct": 0.001,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Agustín Canobbio",
        "team": "Uruguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alex Freeman",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alexander Isak",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ali Iyad Olwan",
        "team": "Jordan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Anthony Elanga",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Bradley Barcola",
        "team": "France",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Breel Embolo",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Cyle Larin",
        "team": "Canada",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Felix Nmecha",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ferran Torres",
        "team": "Spain",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Finn Surman",
        "team": "New Zealand",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gio Reyna",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gonçalo Ramos",
        "team": "Portugal",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Granit Xhaka",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ibrahim Mbaye",
        "team": "Senegal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jamal Musiala",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jude Bellingham",
        "team": "England",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Julián Álvarez",
        "team": "Argentina",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Junya Itō",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kai Havertz",
        "team": "Germany",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Keito Nakamura",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Lamine Yamal",
        "team": "Spain",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Leo Østigård",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Marcus Pedersen",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Marcus Rashford",
        "team": "England",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mattias Svanberg",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Michael Olise",
        "team": "France",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nathan Saliba",
        "team": "Canada",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nathaniel Brown",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nico Schlotterbeck",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nizar Al-Rashdan",
        "team": "Jordan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Omar Rekik",
        "team": "Tunisia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ousmane Dembélé",
        "team": "France",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Raphinha",
        "team": "Brazil",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ruben Vargas",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Viktor Gyökeres",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Virgil van Dijk",
        "team": "Netherlands",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      }
    ],
    "missingParticipantPicks": []
  },
  "modelDetails": {
    "scoreModel": "current_world_cup_weighted_group_plus_historical_knockout_empirical_scorelines",
    "groupCurrentWorldCupWeightPct": 64.7,
    "groupCompletedMatchesUsed": 44,
    "groupObservedDrawRatePct": 29.545,
    "groupHistoricalDrawRatePct": 23.742,
    "groupBlendedDrawRatePct": 27.497,
    "knockoutModel": "historical_recent_weighted_knockout_scorelines",
    "winnerAssignment": "rating-based logistic assignment of higher score to favorite, clipped to [0.28, 0.72]",
    "seed": 20260623,
    "batchSize": 10000
  },
  "gallifantesPrizeSchedule": {
    "first": 750,
    "second": 250,
    "third": 100,
    "rank27": 20,
    "last": 20,
    "tieHandling": "split tied rank block prizes"
  },
  "groupStageLeaderSummary": {
    "sourceFile": "group_stage_leader_after_jordan_algeria.csv"
  }
};
