window.PORRA_ODDS_LATEST = {
  "generatedAt": "2026-06-27T05:11:43Z",
  "label": "After Group G / M66, fresh 300,000 simulations",
  "model": "Monte Carlo amb ranking FIFA + distribució empírica recent de marcadors dels Mundials, amb bonus de Pichichi proxy",
  "simulations": 300000,
  "players": [
    {
      "player": "Aleix",
      "displayName": "Aleix",
      "rank": 1,
      "winPct": 17.452,
      "top3Pct": 42.822,
      "lastPct": 0.0,
      "avgPoints": 911.4,
      "maxPoints": 1243,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 2.29,
      "expectedGallifantes": 177.34,
      "sdGallifantes": 276.06,
      "ceGallifantes": 10.88,
      "ceRank": 1,
      "winDeltaPp": 7.217,
      "top3DeltaPp": 13.244,
      "lastDeltaPp": 0.0,
      "rankDelta": 1,
      "projectedWinner": "Portugal",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Raphinha",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Raphinha (8)",
      "conditionalChampionWinPct": 74.478,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Rafa Bravo",
      "displayName": "Rafa B.",
      "rank": 2,
      "winPct": 14.775,
      "top3Pct": 33.425,
      "lastPct": 0.0,
      "avgPoints": 899.6,
      "maxPoints": 1214,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 145.4,
      "sdGallifantes": 262.8,
      "ceGallifantes": 6.17,
      "ceRank": 2,
      "winDeltaPp": 5.243,
      "top3DeltaPp": 8.086,
      "lastDeltaPp": 0.0,
      "rankDelta": 1,
      "aliases": [
        "Rafa B"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "England",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 47.972,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "JoanRa",
      "displayName": "JoanRa",
      "rank": 3,
      "winPct": 8.574,
      "top3Pct": 18.0,
      "lastPct": 0.004,
      "avgPoints": 865.6,
      "maxPoints": 1251,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 2.29,
      "expectedGallifantes": 81.8,
      "sdGallifantes": 212.19,
      "ceGallifantes": 2.05,
      "ceRank": 3,
      "winDeltaPp": 1.681,
      "top3DeltaPp": 3.478,
      "lastDeltaPp": -0.028,
      "rankDelta": 1,
      "projectedWinner": "Germany",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Kai Havertz",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Kai Havertz (8)",
      "conditionalChampionWinPct": 64.847,
      "projectedChampionWinSims": 20781
    },
    {
      "player": "Joan",
      "displayName": "Joan",
      "rank": 4,
      "winPct": 6.362,
      "top3Pct": 13.74,
      "lastPct": 0.007,
      "avgPoints": 849.6,
      "maxPoints": 1199,
      "pichichiPlayerPct": 62.046,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 9.31,
      "expectedGallifantes": 61.45,
      "sdGallifantes": 186.37,
      "ceGallifantes": 1.38,
      "ceRank": 4,
      "winDeltaPp": 1.047,
      "top3DeltaPp": 1.646,
      "lastDeltaPp": -0.023,
      "rankDelta": 2,
      "projectedWinner": "Argentina",
      "projectedFinalist": "Germany",
      "projectedPichichiName": "Messi",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Messi (6)",
      "conditionalChampionWinPct": 31.129,
      "projectedChampionWinSims": 38288
    },
    {
      "player": "Jordi Raventós",
      "displayName": "Jordi Ra.",
      "rank": 5,
      "winPct": 6.206,
      "top3Pct": 13.351,
      "lastPct": 0.001,
      "avgPoints": 850.2,
      "maxPoints": 1224,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 60.0,
      "sdGallifantes": 184.3,
      "ceGallifantes": 1.35,
      "ceRank": 5,
      "winDeltaPp": -7.906,
      "top3DeltaPp": -13.495,
      "lastDeltaPp": 0.0,
      "rankDelta": -4,
      "aliases": [
        "Jordi Ra",
        "Jordi Ra."
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Morocco",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 30.302,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Nicolau",
      "displayName": "Nicolau",
      "rank": 6,
      "winPct": 5.533,
      "top3Pct": 11.052,
      "lastPct": 0.004,
      "avgPoints": 842.1,
      "maxPoints": 1233,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 51.89,
      "sdGallifantes": 174.5,
      "ceGallifantes": 1.07,
      "ceRank": 7,
      "winDeltaPp": 0.026,
      "top3DeltaPp": 0.114,
      "lastDeltaPp": -0.025,
      "rankDelta": -1,
      "projectedWinner": "Brazil",
      "projectedFinalist": "Netherlands",
      "projectedPichichiName": "Raphinha",
      "projectedPichichiGoals": 5,
      "projectedPichichi": "Raphinha (5)",
      "conditionalChampionWinPct": 40.814,
      "projectedChampionWinSims": 17400
    },
    {
      "player": "Miquel",
      "displayName": "Miquel",
      "rank": 7,
      "winPct": 3.906,
      "top3Pct": 14.689,
      "lastPct": 0.0,
      "avgPoints": 879.9,
      "maxPoints": 1193,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 1.27,
      "expectedGallifantes": 47.99,
      "sdGallifantes": 152.57,
      "ceGallifantes": 1.34,
      "ceRank": 6,
      "winDeltaPp": 0.73,
      "top3DeltaPp": 3.022,
      "lastDeltaPp": 0.0,
      "rankDelta": 2,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Harry Kane (7)",
      "conditionalChampionWinPct": 12.041,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Carlo",
      "displayName": "Carlo",
      "rank": 8,
      "winPct": 3.563,
      "top3Pct": 8.569,
      "lastPct": 0.0,
      "avgPoints": 854.4,
      "maxPoints": 1188,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.2,
      "expectedGallifantes": 36.16,
      "sdGallifantes": 143.33,
      "ceGallifantes": 0.79,
      "ceRank": 14,
      "winDeltaPp": -1.686,
      "top3DeltaPp": -3.903,
      "lastDeltaPp": 0.0,
      "rankDelta": -1,
      "projectedWinner": "England",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 5,
      "projectedPichichi": "Harry Kane (5)",
      "conditionalChampionWinPct": 38.566,
      "projectedChampionWinSims": 22029
    },
    {
      "player": "Chús",
      "displayName": "Chús",
      "rank": 9,
      "winPct": 3.281,
      "top3Pct": 10.492,
      "lastPct": 0.0,
      "avgPoints": 863.1,
      "maxPoints": 1248,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 37.52,
      "sdGallifantes": 139.74,
      "ceGallifantes": 0.94,
      "ceRank": 11,
      "winDeltaPp": 0.202,
      "top3DeltaPp": 0.93,
      "lastDeltaPp": -0.001,
      "rankDelta": 1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Ferran Torres",
      "projectedPichichiGoals": 5,
      "projectedPichichi": "Ferran Torres (5)",
      "conditionalChampionWinPct": 13.778,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Juanma",
      "displayName": "Juanma",
      "rank": 10,
      "winPct": 2.937,
      "top3Pct": 11.14,
      "lastPct": 0.0,
      "avgPoints": 871.6,
      "maxPoints": 1222,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 36.28,
      "sdGallifantes": 133.85,
      "ceGallifantes": 0.96,
      "ceRank": 10,
      "winDeltaPp": 0.903,
      "top3DeltaPp": 3.395,
      "lastDeltaPp": 0.0,
      "rankDelta": 7,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 12.892,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Oscar Bordas",
      "displayName": "Oscar B.",
      "rank": 11,
      "winPct": 2.857,
      "top3Pct": 10.719,
      "lastPct": 0.0,
      "avgPoints": 873.6,
      "maxPoints": 1215,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 34.94,
      "sdGallifantes": 131.91,
      "ceGallifantes": 0.9,
      "ceRank": 12,
      "winDeltaPp": -0.077,
      "top3DeltaPp": 0.265,
      "lastDeltaPp": 0.0,
      "rankDelta": 1,
      "aliases": [
        "Oscar B"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 14.059,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Emiliano",
      "displayName": "Emiliano",
      "rank": 12,
      "winPct": 2.067,
      "top3Pct": 11.518,
      "lastPct": 0.0,
      "avgPoints": 872.6,
      "maxPoints": 1183,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 31.89,
      "sdGallifantes": 117.33,
      "ceGallifantes": 0.97,
      "ceRank": 9,
      "winDeltaPp": 0.52,
      "top3DeltaPp": 3.428,
      "lastDeltaPp": 0.0,
      "rankDelta": 7,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 4.654,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Andy",
      "displayName": "Andy",
      "rank": 13,
      "winPct": 2.054,
      "top3Pct": 5.81,
      "lastPct": 0.0,
      "avgPoints": 853.8,
      "maxPoints": 1136,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 22.4,
      "sdGallifantes": 111.05,
      "ceGallifantes": 0.53,
      "ceRank": 19,
      "winDeltaPp": 0.056,
      "top3DeltaPp": 0.35,
      "lastDeltaPp": 0.0,
      "rankDelta": 5,
      "projectedWinner": "Colombia",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 41.381,
      "projectedChampionWinSims": 10456
    },
    {
      "player": "Bernat Orriols",
      "displayName": "Bernat O.",
      "rank": 14,
      "winPct": 1.926,
      "top3Pct": 5.034,
      "lastPct": 0.009,
      "avgPoints": 830.7,
      "maxPoints": 1159,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 2.83,
      "expectedGallifantes": 20.46,
      "sdGallifantes": 107.36,
      "ceGallifantes": 0.46,
      "ceRank": 22,
      "winDeltaPp": 0.955,
      "top3DeltaPp": 2.069,
      "lastDeltaPp": -0.194,
      "rankDelta": 9,
      "aliases": [
        "Bernat O"
      ],
      "projectedWinner": "Argentina",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Mbappé (6)",
      "conditionalChampionWinPct": 13.276,
      "projectedChampionWinSims": 38288
    },
    {
      "player": "Pablo",
      "displayName": "Pablo",
      "rank": 15,
      "winPct": 1.894,
      "top3Pct": 11.659,
      "lastPct": 0.0,
      "avgPoints": 870.6,
      "maxPoints": 1238,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 31.95,
      "sdGallifantes": 114.83,
      "ceGallifantes": 1.0,
      "ceRank": 8,
      "winDeltaPp": -1.337,
      "top3DeltaPp": -2.115,
      "lastDeltaPp": 0.0,
      "rankDelta": -7,
      "projectedWinner": "Portugal",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 8.202,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Sergi Sanromà",
      "displayName": "Sergi S.",
      "rank": 16,
      "winPct": 1.809,
      "top3Pct": 7.42,
      "lastPct": 0.0,
      "avgPoints": 860.4,
      "maxPoints": 1202,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 23.44,
      "sdGallifantes": 107.03,
      "ceGallifantes": 0.62,
      "ceRank": 16,
      "winDeltaPp": -1.116,
      "top3DeltaPp": -2.884,
      "lastDeltaPp": 0.0,
      "rankDelta": -3,
      "aliases": [
        "Sergi S"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 8.487,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Oscar Campanyà",
      "displayName": "Oscar C.",
      "rank": 17,
      "winPct": 1.628,
      "top3Pct": 5.544,
      "lastPct": 0.001,
      "avgPoints": 842.3,
      "maxPoints": 1176,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 19.8,
      "sdGallifantes": 101.03,
      "ceGallifantes": 0.51,
      "ceRank": 21,
      "winDeltaPp": -0.439,
      "top3DeltaPp": -0.814,
      "lastDeltaPp": -0.004,
      "rankDelta": -1,
      "aliases": [
        "Oscar C"
      ],
      "projectedWinner": "Argentina",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 12.179,
      "projectedChampionWinSims": 38288
    },
    {
      "player": "Marc",
      "displayName": "Marc",
      "rank": 18,
      "winPct": 1.211,
      "top3Pct": 5.06,
      "lastPct": 0.0,
      "avgPoints": 856.1,
      "maxPoints": 1206,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 0.07,
      "expectedGallifantes": 15.98,
      "sdGallifantes": 88.29,
      "ceGallifantes": 0.44,
      "ceRank": 26,
      "winDeltaPp": 0.607,
      "top3DeltaPp": 2.423,
      "lastDeltaPp": -0.008,
      "rankDelta": 9,
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Julián Álvarez",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Julián Álvarez (7)",
      "conditionalChampionWinPct": 6.428,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Bernat Garreta",
      "displayName": "Bernat G.",
      "rank": 19,
      "winPct": 1.117,
      "top3Pct": 3.393,
      "lastPct": 0.062,
      "avgPoints": 807.2,
      "maxPoints": 1172,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.2,
      "expectedGallifantes": 12.7,
      "sdGallifantes": 83.2,
      "ceGallifantes": 0.29,
      "ceRank": 30,
      "winDeltaPp": -0.416,
      "top3DeltaPp": -1.184,
      "lastDeltaPp": -0.139,
      "rankDelta": 1,
      "aliases": [
        "Bernat G"
      ],
      "projectedWinner": "England",
      "projectedFinalist": "Morocco",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 15,
      "projectedPichichi": "Harry Kane (15)",
      "conditionalChampionWinPct": 10.495,
      "projectedChampionWinSims": 22029
    },
    {
      "player": "Rubi",
      "displayName": "Rubi",
      "rank": 20,
      "winPct": 0.982,
      "top3Pct": 5.067,
      "lastPct": 0.0,
      "avgPoints": 846.7,
      "maxPoints": 1162,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 14.81,
      "sdGallifantes": 81.64,
      "ceGallifantes": 0.45,
      "ceRank": 24,
      "winDeltaPp": -1.513,
      "top3DeltaPp": -4.271,
      "lastDeltaPp": 0.0,
      "rankDelta": -6,
      "projectedWinner": "Portugal",
      "projectedFinalist": "France",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 7.167,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Oriol Valls",
      "displayName": "Oriol V.",
      "rank": 21,
      "winPct": 0.941,
      "top3Pct": 3.869,
      "lastPct": 0.001,
      "avgPoints": 842.6,
      "maxPoints": 1183,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 1.27,
      "expectedGallifantes": 12.63,
      "sdGallifantes": 78.28,
      "ceGallifantes": 0.37,
      "ceRank": 28,
      "winDeltaPp": 0.545,
      "top3DeltaPp": 2.047,
      "lastDeltaPp": -0.064,
      "rankDelta": 9,
      "aliases": [
        "Oriol V"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Harry Kane (7)",
      "conditionalChampionWinPct": 4.154,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Pau",
      "displayName": "Pau",
      "rank": 22,
      "winPct": 0.858,
      "top3Pct": 5.372,
      "lastPct": 0.0,
      "avgPoints": 857.9,
      "maxPoints": 1175,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 14.13,
      "sdGallifantes": 77.4,
      "ceGallifantes": 0.45,
      "ceRank": 23,
      "winDeltaPp": 0.31,
      "top3DeltaPp": 1.908,
      "lastDeltaPp": -0.001,
      "rankDelta": 6,
      "projectedWinner": "France",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 4.126,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Guille Amor",
      "displayName": "Guille A.",
      "rank": 23,
      "winPct": 0.791,
      "top3Pct": 2.745,
      "lastPct": 0.061,
      "avgPoints": 816.4,
      "maxPoints": 1154,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.2,
      "expectedGallifantes": 9.81,
      "sdGallifantes": 71.07,
      "ceGallifantes": 0.26,
      "ceRank": 36,
      "winDeltaPp": -0.233,
      "top3DeltaPp": -0.489,
      "lastDeltaPp": -0.222,
      "rankDelta": -1,
      "aliases": [
        "Guille A"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Harry Kane (6)",
      "conditionalChampionWinPct": 3.824,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Jaume Cardús",
      "displayName": "Jaume C.",
      "rank": 24,
      "winPct": 0.784,
      "top3Pct": 3.449,
      "lastPct": 0.001,
      "avgPoints": 832.4,
      "maxPoints": 1163,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 2.29,
      "expectedGallifantes": 11.23,
      "sdGallifantes": 72.49,
      "ceGallifantes": 0.35,
      "ceRank": 29,
      "winDeltaPp": 0.139,
      "top3DeltaPp": 0.798,
      "lastDeltaPp": -0.001,
      "rankDelta": 1,
      "aliases": [
        "Jaume C"
      ],
      "projectedWinner": "Brazil",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Raphinha",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Raphinha (8)",
      "conditionalChampionWinPct": 12.707,
      "projectedChampionWinSims": 17400
    },
    {
      "player": "Antonio",
      "displayName": "Antonio",
      "rank": 25,
      "winPct": 0.747,
      "top3Pct": 2.855,
      "lastPct": 0.047,
      "avgPoints": 818.3,
      "maxPoints": 1190,
      "pichichiPlayerPct": 5.417,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.81,
      "expectedGallifantes": 9.7,
      "sdGallifantes": 69.64,
      "ceGallifantes": 0.26,
      "ceRank": 35,
      "winDeltaPp": -1.731,
      "top3DeltaPp": -4.784,
      "lastDeltaPp": 0.019,
      "rankDelta": -10,
      "projectedWinner": "Argentina",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Haaland",
      "projectedPichichiGoals": 4,
      "projectedPichichi": "Haaland (4)",
      "conditionalChampionWinPct": 5.235,
      "projectedChampionWinSims": 38288
    },
    {
      "player": "Bernat Raventós",
      "displayName": "Bernat R.",
      "rank": 26,
      "winPct": 0.741,
      "top3Pct": 4.475,
      "lastPct": 0.0,
      "avgPoints": 850.9,
      "maxPoints": 1134,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 12.32,
      "sdGallifantes": 72.37,
      "ceGallifantes": 0.39,
      "ceRank": 27,
      "winDeltaPp": -2.196,
      "top3DeltaPp": -9.739,
      "lastDeltaPp": 0.0,
      "rankDelta": -15,
      "aliases": [
        "Bernat R"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 2.695,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Pol",
      "displayName": "Pol",
      "rank": 27,
      "winPct": 0.647,
      "top3Pct": 5.491,
      "lastPct": 0.0,
      "avgPoints": 861.4,
      "maxPoints": 1155,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 13.03,
      "sdGallifantes": 70.24,
      "ceGallifantes": 0.44,
      "ceRank": 25,
      "winDeltaPp": 0.013,
      "top3DeltaPp": 1.05,
      "lastDeltaPp": 0.0,
      "rankDelta": -1,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 0.983,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Isra",
      "displayName": "Isra",
      "rank": 28,
      "winPct": 0.544,
      "top3Pct": 2.606,
      "lastPct": 0.0,
      "avgPoints": 843.7,
      "maxPoints": 1200,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 42.146,
      "pichichiExpPoints": 7.05,
      "expectedGallifantes": 8.08,
      "sdGallifantes": 60.42,
      "ceGallifantes": 0.28,
      "ceRank": 31,
      "winDeltaPp": 0.135,
      "top3DeltaPp": 0.568,
      "lastDeltaPp": -0.002,
      "rankDelta": 1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 9,
      "projectedPichichi": "Mbappé (9)",
      "conditionalChampionWinPct": 2.374,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Biel",
      "displayName": "Biel",
      "rank": 29,
      "winPct": 0.524,
      "top3Pct": 2.283,
      "lastPct": 0.259,
      "avgPoints": 800.1,
      "maxPoints": 1142,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 7.31,
      "sdGallifantes": 59.25,
      "ceGallifantes": 0.2,
      "ceRank": 40,
      "winDeltaPp": -0.901,
      "top3DeltaPp": -3.683,
      "lastDeltaPp": 0.163,
      "rankDelta": -8,
      "projectedWinner": "France",
      "projectedFinalist": "Norway",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 3.297,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Oriol Oltra",
      "displayName": "Oriol O.",
      "rank": 30,
      "winPct": 0.436,
      "top3Pct": 2.537,
      "lastPct": 0.0,
      "avgPoints": 845.0,
      "maxPoints": 1184,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 7.27,
      "sdGallifantes": 55.12,
      "ceGallifantes": 0.28,
      "ceRank": 32,
      "winDeltaPp": 0.133,
      "top3DeltaPp": 0.785,
      "lastDeltaPp": -0.001,
      "rankDelta": 2,
      "aliases": [
        "Oriol O"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 2.121,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Jordi Ollé",
      "displayName": "Jordi O.",
      "rank": 31,
      "winPct": 0.426,
      "top3Pct": 2.428,
      "lastPct": 0.0,
      "avgPoints": 843.7,
      "maxPoints": 1167,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 7.06,
      "sdGallifantes": 54.41,
      "ceGallifantes": 0.27,
      "ceRank": 33,
      "winDeltaPp": 0.079,
      "top3DeltaPp": 0.449,
      "lastDeltaPp": 0.0,
      "rankDelta": 0,
      "aliases": [
        "Jordi O"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 2.487,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Daniela",
      "displayName": "Daniela",
      "rank": 32,
      "winPct": 0.403,
      "top3Pct": 1.483,
      "lastPct": 0.014,
      "avgPoints": 821.8,
      "maxPoints": 1146,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 5.42,
      "sdGallifantes": 51.01,
      "ceGallifantes": 0.2,
      "ceRank": 39,
      "winDeltaPp": 0.107,
      "top3DeltaPp": 0.381,
      "lastDeltaPp": -0.138,
      "rankDelta": 1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Brazil",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 2.854,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Xavi Ferrés",
      "displayName": "Xavi F.",
      "rank": 33,
      "winPct": 0.289,
      "top3Pct": 1.245,
      "lastPct": 0.004,
      "avgPoints": 820.2,
      "maxPoints": 1187,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 4.26,
      "sdGallifantes": 43.83,
      "ceGallifantes": 0.17,
      "ceRank": 43,
      "winDeltaPp": 0.062,
      "top3DeltaPp": 0.291,
      "lastDeltaPp": -0.075,
      "rankDelta": 3,
      "aliases": [
        "Xavi F"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 1.558,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Manu GS",
      "displayName": "Manu G.",
      "rank": 34,
      "winPct": 0.246,
      "top3Pct": 1.081,
      "lastPct": 0.036,
      "avgPoints": 808.1,
      "maxPoints": 1210,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.2,
      "expectedGallifantes": 3.6,
      "sdGallifantes": 40.46,
      "ceGallifantes": 0.14,
      "ceRank": 48,
      "winDeltaPp": 0.014,
      "top3DeltaPp": 0.095,
      "lastDeltaPp": -0.07,
      "rankDelta": 1,
      "aliases": [
        "Manu G"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Harry Kane (6)",
      "conditionalChampionWinPct": 1.285,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Martina",
      "displayName": "Martina",
      "rank": 35,
      "winPct": 0.244,
      "top3Pct": 1.707,
      "lastPct": 0.003,
      "avgPoints": 835.4,
      "maxPoints": 1179,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 4.73,
      "sdGallifantes": 42.3,
      "ceGallifantes": 0.21,
      "ceRank": 37,
      "winDeltaPp": -0.007,
      "top3DeltaPp": 0.058,
      "lastDeltaPp": -0.004,
      "rankDelta": -1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 1.155,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Rafa Angulo",
      "displayName": "Rafa A.",
      "rank": 36,
      "winPct": 0.216,
      "top3Pct": 1.122,
      "lastPct": 0.055,
      "avgPoints": 816.7,
      "maxPoints": 1219,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 0.07,
      "expectedGallifantes": 3.6,
      "sdGallifantes": 38.69,
      "ceGallifantes": 0.16,
      "ceRank": 45,
      "winDeltaPp": 0.087,
      "top3DeltaPp": 0.43,
      "lastDeltaPp": -0.398,
      "rankDelta": 5,
      "aliases": [
        "Rafa A"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Lamine Yamal",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Lamine Yamal (7)",
      "conditionalChampionWinPct": 1.326,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Albert Cosí",
      "displayName": "Albert C.",
      "rank": 37,
      "winPct": 0.19,
      "top3Pct": 0.559,
      "lastPct": 11.862,
      "avgPoints": 742.1,
      "maxPoints": 1046,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 1.27,
      "expectedGallifantes": 4.55,
      "sdGallifantes": 34.95,
      "ceGallifantes": 0.52,
      "ceRank": 20,
      "winDeltaPp": -0.648,
      "top3DeltaPp": -1.639,
      "lastDeltaPp": 6.867,
      "rankDelta": -13,
      "aliases": [
        "Albert C"
      ],
      "projectedWinner": "Argentina",
      "projectedFinalist": "Netherlands",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Harry Kane (7)",
      "conditionalChampionWinPct": 1.228,
      "projectedChampionWinSims": 38288
    },
    {
      "player": "David Muñoz",
      "displayName": "David M.",
      "rank": 38,
      "winPct": 0.182,
      "top3Pct": 1.127,
      "lastPct": 0.003,
      "avgPoints": 827.5,
      "maxPoints": 1168,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 3.49,
      "expectedGallifantes": 3.46,
      "sdGallifantes": 36.07,
      "ceGallifantes": 0.18,
      "ceRank": 42,
      "winDeltaPp": 0.04,
      "top3DeltaPp": 0.294,
      "lastDeltaPp": -0.013,
      "rankDelta": 2,
      "aliases": [
        "David M"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Harry Kane (8)",
      "conditionalChampionWinPct": 0.848,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Michael",
      "displayName": "Michael",
      "rank": 39,
      "winPct": 0.164,
      "top3Pct": 1.747,
      "lastPct": 0.001,
      "avgPoints": 840.8,
      "maxPoints": 1140,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 2.83,
      "expectedGallifantes": 4.23,
      "sdGallifantes": 36.83,
      "ceGallifantes": 0.21,
      "ceRank": 38,
      "winDeltaPp": 0.072,
      "top3DeltaPp": 0.919,
      "lastDeltaPp": -0.01,
      "rankDelta": 6,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Mbappé (6)",
      "conditionalChampionWinPct": 0.493,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Jordi Reig",
      "displayName": "Jordi Re.",
      "rank": 40,
      "winPct": 0.125,
      "top3Pct": 0.771,
      "lastPct": 0.028,
      "avgPoints": 811.4,
      "maxPoints": 1159,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 1.27,
      "expectedGallifantes": 2.44,
      "sdGallifantes": 30.07,
      "ceGallifantes": 0.13,
      "ceRank": 49,
      "winDeltaPp": 0.023,
      "top3DeltaPp": 0.209,
      "lastDeltaPp": -0.146,
      "rankDelta": 3,
      "aliases": [
        "Jordi Re",
        "Jordi Re."
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "England",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Harry Kane (7)",
      "conditionalChampionWinPct": 0.687,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Teo",
      "displayName": "Teo",
      "rank": 41,
      "winPct": 0.089,
      "top3Pct": 0.72,
      "lastPct": 0.003,
      "avgPoints": 831.7,
      "maxPoints": 1182,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 2.24,
      "sdGallifantes": 26.05,
      "ceGallifantes": 0.16,
      "ceRank": 44,
      "winDeltaPp": -0.135,
      "top3DeltaPp": -0.563,
      "lastDeltaPp": 0.0,
      "rankDelta": -4,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 0.556,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Paco",
      "displayName": "Paco",
      "rank": 42,
      "winPct": 0.077,
      "top3Pct": 0.355,
      "lastPct": 2.542,
      "avgPoints": 770.8,
      "maxPoints": 1048,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 1.75,
      "sdGallifantes": 22.99,
      "ceGallifantes": 0.15,
      "ceRank": 46,
      "winDeltaPp": -0.109,
      "top3DeltaPp": -0.521,
      "lastDeltaPp": -0.338,
      "rankDelta": -4,
      "projectedWinner": "Argentina",
      "projectedFinalist": "France",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 0.563,
      "projectedChampionWinSims": 38288
    },
    {
      "player": "Norber",
      "displayName": "Norber",
      "rank": 43,
      "winPct": 0.073,
      "top3Pct": 0.337,
      "lastPct": 0.455,
      "avgPoints": 788.8,
      "maxPoints": 1186,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 3.49,
      "expectedGallifantes": 1.33,
      "sdGallifantes": 22.29,
      "ceGallifantes": 0.08,
      "ceRank": 51,
      "winDeltaPp": -0.002,
      "top3DeltaPp": -0.013,
      "lastDeltaPp": -0.812,
      "rankDelta": 5,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Harry Kane (8)",
      "conditionalChampionWinPct": 0.359,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Enrique Moral",
      "displayName": "Enrique M.",
      "rank": 44,
      "winPct": 0.042,
      "top3Pct": 0.312,
      "lastPct": 14.551,
      "avgPoints": 737.1,
      "maxPoints": 1086,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.2,
      "expectedGallifantes": 3.79,
      "sdGallifantes": 19.39,
      "ceGallifantes": 0.62,
      "ceRank": 17,
      "winDeltaPp": 0.011,
      "top3DeltaPp": 0.046,
      "lastDeltaPp": -4.288,
      "rankDelta": 6,
      "aliases": [
        "Enrique M"
      ],
      "projectedWinner": "Germany",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 5,
      "projectedPichichi": "Harry Kane (5)",
      "conditionalChampionWinPct": 0.585,
      "projectedChampionWinSims": 20781
    },
    {
      "player": "Jordi Cunyao",
      "displayName": "Jordi C.",
      "rank": 45,
      "winPct": 0.031,
      "top3Pct": 0.223,
      "lastPct": 6.483,
      "avgPoints": 755.4,
      "maxPoints": 1022,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 2.9,
      "expectedGallifantes": 1.99,
      "sdGallifantes": 16.0,
      "ceGallifantes": 0.27,
      "ceRank": 34,
      "winDeltaPp": -0.143,
      "top3DeltaPp": -0.752,
      "lastDeltaPp": 1.492,
      "rankDelta": -6,
      "aliases": [
        "Jordi C"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Brazil",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Mbappé (7)",
      "conditionalChampionWinPct": 0.04,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Toni Campanyà",
      "displayName": "Toni C.",
      "rank": 46,
      "winPct": 0.023,
      "top3Pct": 0.144,
      "lastPct": 2.458,
      "avgPoints": 763.3,
      "maxPoints": 1038,
      "pichichiPlayerPct": 5.417,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 3.1,
      "expectedGallifantes": 1.01,
      "sdGallifantes": 13.39,
      "ceGallifantes": 0.12,
      "ceRank": 50,
      "winDeltaPp": -0.013,
      "top3DeltaPp": -0.022,
      "lastDeltaPp": -2.907,
      "rankDelta": 3,
      "aliases": [
        "Toni C"
      ],
      "projectedWinner": "Brazil",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Haaland",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Haaland (8)",
      "conditionalChampionWinPct": 0.241,
      "projectedChampionWinSims": 17400
    },
    {
      "player": "Albert Esteve",
      "displayName": "Albert E.",
      "rank": 47,
      "winPct": 0.007,
      "top3Pct": 0.048,
      "lastPct": 4.797,
      "avgPoints": 750.2,
      "maxPoints": 1105,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 0.07,
      "expectedGallifantes": 1.18,
      "sdGallifantes": 8.63,
      "ceGallifantes": 0.18,
      "ceRank": 41,
      "winDeltaPp": -0.079,
      "top3DeltaPp": -0.397,
      "lastDeltaPp": 3.159,
      "rankDelta": -1,
      "aliases": [
        "Albert E"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "Netherlands",
      "projectedPichichiName": "Gonçalo Ramos",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Gonçalo Ramos (7)",
      "conditionalChampionWinPct": 0.113,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Eduard Verdaguer",
      "displayName": "Eduard V.",
      "rank": 48,
      "winPct": 0.007,
      "top3Pct": 0.045,
      "lastPct": 19.005,
      "avgPoints": 726.2,
      "maxPoints": 1031,
      "pichichiPlayerPct": 7.995,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.2,
      "expectedGallifantes": 3.98,
      "sdGallifantes": 10.51,
      "ceGallifantes": 0.82,
      "ceRank": 13,
      "winDeltaPp": -0.086,
      "top3DeltaPp": -0.437,
      "lastDeltaPp": 11.656,
      "rankDelta": -4,
      "aliases": [
        "Eduard V"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "England",
      "projectedPichichiName": "Harry Kane",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Harry Kane (6)",
      "conditionalChampionWinPct": 0.016,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Manel Pujol",
      "displayName": "Manel P.",
      "rank": 49,
      "winPct": 0.006,
      "top3Pct": 0.041,
      "lastPct": 16.152,
      "avgPoints": 729.0,
      "maxPoints": 986,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 3.41,
      "sdGallifantes": 9.95,
      "ceGallifantes": 0.67,
      "ceRank": 15,
      "winDeltaPp": -0.071,
      "top3DeltaPp": -0.383,
      "lastDeltaPp": 9.159,
      "rankDelta": -2,
      "aliases": [
        "Manel P"
      ],
      "projectedWinner": "France",
      "projectedFinalist": "Brazil",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 0.003,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Guillem Ochoa",
      "displayName": "Guillem O.",
      "rank": 50,
      "winPct": 0.005,
      "top3Pct": 0.063,
      "lastPct": 0.272,
      "avgPoints": 791.2,
      "maxPoints": 1118,
      "pichichiPlayerPct": 0.244,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.04,
      "expectedGallifantes": 0.46,
      "sdGallifantes": 7.08,
      "ceGallifantes": 0.07,
      "ceRank": 54,
      "winDeltaPp": -0.108,
      "top3DeltaPp": -0.665,
      "lastDeltaPp": 0.207,
      "rankDelta": -8,
      "aliases": [
        "Guillem O"
      ],
      "projectedWinner": "Spain",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Oyarzábal",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Oyarzábal (6)",
      "conditionalChampionWinPct": 0.028,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Jaume Martí",
      "displayName": "Jaume M.",
      "rank": 51,
      "winPct": 0.005,
      "top3Pct": 0.049,
      "lastPct": 0.229,
      "avgPoints": 780.5,
      "maxPoints": 1124,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.696,
      "pichichiExpPoints": 0.07,
      "expectedGallifantes": 0.35,
      "sdGallifantes": 6.28,
      "ceGallifantes": 0.05,
      "ceRank": 57,
      "winDeltaPp": 0.004,
      "top3DeltaPp": 0.034,
      "lastDeltaPp": -1.138,
      "rankDelta": 4,
      "aliases": [
        "Jaume M"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "France",
      "projectedPichichiName": "Olise",
      "projectedPichichiGoals": 7,
      "projectedPichichi": "Olise (7)",
      "conditionalChampionWinPct": 0.066,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Pere",
      "displayName": "Pere",
      "rank": 52,
      "winPct": 0.002,
      "top3Pct": 0.033,
      "lastPct": 0.105,
      "avgPoints": 796.9,
      "maxPoints": 1128,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 2.83,
      "expectedGallifantes": 0.46,
      "sdGallifantes": 5.05,
      "ceGallifantes": 0.08,
      "ceRank": 53,
      "winDeltaPp": 0.0,
      "top3DeltaPp": -0.01,
      "lastDeltaPp": -0.168,
      "rankDelta": 2,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 13,
      "projectedPichichi": "Mbappé (13)",
      "conditionalChampionWinPct": 0.016,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Nick",
      "displayName": "Nick",
      "rank": 53,
      "winPct": 0.001,
      "top3Pct": 0.017,
      "lastPct": 1.835,
      "avgPoints": 764.9,
      "maxPoints": 1070,
      "pichichiPlayerPct": 0.0,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 0.0,
      "expectedGallifantes": 0.52,
      "sdGallifantes": 4.4,
      "ceGallifantes": 0.08,
      "ceRank": 52,
      "winDeltaPp": -0.003,
      "top3DeltaPp": -0.013,
      "lastDeltaPp": -1.44,
      "rankDelta": -1,
      "projectedWinner": "Spain",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Ferran Torres",
      "projectedPichichiGoals": 6,
      "projectedPichichi": "Ferran Torres (6)",
      "conditionalChampionWinPct": 0.006,
      "projectedChampionWinSims": 24906
    },
    {
      "player": "Albert Benach",
      "displayName": "Albert B.",
      "rank": 54,
      "winPct": 0.0,
      "top3Pct": 0.008,
      "lastPct": 13.745,
      "avgPoints": 726.7,
      "maxPoints": 1065,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 2.83,
      "expectedGallifantes": 2.8,
      "sdGallifantes": 7.07,
      "ceGallifantes": 0.54,
      "ceRank": 18,
      "winDeltaPp": 0.0,
      "top3DeltaPp": 0.007,
      "lastDeltaPp": -13.466,
      "rankDelta": 2,
      "aliases": [
        "Albert B"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "France",
      "projectedPichichiName": "Dembélé",
      "projectedPichichiGoals": 5,
      "projectedPichichi": "Dembélé (5)",
      "conditionalChampionWinPct": 0.0,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Andreu",
      "displayName": "Andreu",
      "rank": 55,
      "winPct": 0.0,
      "top3Pct": 0.005,
      "lastPct": 3.397,
      "avgPoints": 760.0,
      "maxPoints": 1078,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 0.83,
      "sdGallifantes": 4.0,
      "ceGallifantes": 0.14,
      "ceRank": 47,
      "winDeltaPp": -0.004,
      "top3DeltaPp": -0.024,
      "lastDeltaPp": -0.757,
      "rankDelta": -4,
      "projectedWinner": "France",
      "projectedFinalist": "Portugal",
      "projectedPichichiName": "Dembélé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Dembélé (8)",
      "conditionalChampionWinPct": 0.0,
      "projectedChampionWinSims": 31633
    },
    {
      "player": "Eduardo Morales",
      "displayName": "Eduardo M.",
      "rank": 56,
      "winPct": 0.0,
      "top3Pct": 0.148,
      "lastPct": 0.297,
      "avgPoints": 786.1,
      "maxPoints": 1162,
      "pichichiPlayerPct": 12.436,
      "pichichiGoalsPct": 0.0,
      "pichichiExpPoints": 1.87,
      "expectedGallifantes": 0.45,
      "sdGallifantes": 5.07,
      "ceGallifantes": 0.06,
      "ceRank": 56,
      "winDeltaPp": -0.004,
      "top3DeltaPp": -0.014,
      "lastDeltaPp": -0.093,
      "rankDelta": -3,
      "aliases": [
        "Eduardo M"
      ],
      "projectedWinner": "Portugal",
      "projectedFinalist": "Spain",
      "projectedPichichiName": "Vinicius",
      "projectedPichichiGoals": 5,
      "projectedPichichi": "Vinicius (5)",
      "conditionalChampionWinPct": 0.0,
      "projectedChampionWinSims": 19029
    },
    {
      "player": "Gerard",
      "displayName": "Gerard",
      "rank": 57,
      "winPct": 0.0,
      "top3Pct": 0.0,
      "lastPct": 1.211,
      "avgPoints": 763.9,
      "maxPoints": 1028,
      "pichichiPlayerPct": 18.888,
      "pichichiGoalsPct": 22.862,
      "pichichiExpPoints": 5.12,
      "expectedGallifantes": 0.37,
      "sdGallifantes": 2.6,
      "ceGallifantes": 0.06,
      "ceRank": 55,
      "winDeltaPp": 0.0,
      "top3DeltaPp": 0.0,
      "lastDeltaPp": -5.751,
      "rankDelta": 0,
      "projectedWinner": "France",
      "projectedFinalist": "Argentina",
      "projectedPichichiName": "Mbappé",
      "projectedPichichiGoals": 8,
      "projectedPichichi": "Mbappé (8)",
      "conditionalChampionWinPct": 0.0,
      "projectedChampionWinSims": 31633
    }
  ],
  "pichichi": {
    "asOf": "27 Jun 2026, after Group G completed (66 matches played; Belgium group finished)",
    "source": "Manual update from confirmed scorer reports through Group G completion: Spain 1-0 Uruguay; Cabo Verde 0-0 Saudi Arabia; Belgium 5-1 New Zealand; Egypt 1-1 IR Iran.",
    "method": "current_goals_plus_future_team_matches",
    "playerBonusPoints": 15,
    "goalTotalBonusPoints": 10,
    "goalTotalDistribution": [
      {
        "goals": 7,
        "pct": 0.696
      },
      {
        "goals": 8,
        "pct": 22.862
      },
      {
        "goals": 9,
        "pct": 42.146
      },
      {
        "goals": 11,
        "pct": 34.295
      }
    ],
    "trackedPlayers": [
      {
        "player": "Lionel Messi",
        "team": "Argentina",
        "currentGoals": 5,
        "topPct": 62.046,
        "tieSplitTopPct": 50.323
      },
      {
        "player": "Kylian Mbappé",
        "team": "France",
        "currentGoals": 4,
        "topPct": 18.888,
        "tieSplitTopPct": 8.348
      },
      {
        "player": "Ousmane Dembélé",
        "team": "France",
        "currentGoals": 4,
        "topPct": 18.888,
        "tieSplitTopPct": 8.348
      },
      {
        "player": "Vinícius Júnior",
        "team": "Brazil",
        "currentGoals": 4,
        "topPct": 12.436,
        "tieSplitTopPct": 10.296
      },
      {
        "player": "Harry Kane",
        "team": "England",
        "currentGoals": 2,
        "topPct": 7.995,
        "tieSplitTopPct": 3.218
      },
      {
        "player": "Deniz Undav",
        "team": "Germany",
        "currentGoals": 3,
        "topPct": 6.557,
        "tieSplitTopPct": 3.304
      },
      {
        "player": "Brian Brobbey",
        "team": "Netherlands",
        "currentGoals": 3,
        "topPct": 6.095,
        "tieSplitTopPct": 3.058
      },
      {
        "player": "Cristiano Ronaldo",
        "team": "Portugal",
        "currentGoals": 2,
        "topPct": 5.578,
        "tieSplitTopPct": 2.226
      },
      {
        "player": "Erling Haaland",
        "team": "Norway",
        "currentGoals": 4,
        "topPct": 5.417,
        "tieSplitTopPct": 3.393
      },
      {
        "player": "Daniel Muñoz",
        "team": "Colombia",
        "currentGoals": 2,
        "topPct": 4.159,
        "tieSplitTopPct": 1.644
      },
      {
        "player": "Ismael Saibari",
        "team": "Morocco",
        "currentGoals": 3,
        "topPct": 3.626,
        "tieSplitTopPct": 1.82
      },
      {
        "player": "Johan Manzambi",
        "team": "Switzerland",
        "currentGoals": 3,
        "topPct": 3.369,
        "tieSplitTopPct": 1.365
      },
      {
        "player": "Ismaïla Sarr",
        "team": "Senegal",
        "currentGoals": 3,
        "topPct": 2.703,
        "tieSplitTopPct": 1.191
      },
      {
        "player": "Jonathan David",
        "team": "Canada",
        "currentGoals": 3,
        "topPct": 2.021,
        "tieSplitTopPct": 1.016
      },
      {
        "player": "Mikel Oyarzabal",
        "team": "Spain",
        "currentGoals": 2,
        "topPct": 0.244,
        "tieSplitTopPct": 0.054
      },
      {
        "player": "Julián Quiñones",
        "team": "Mexico",
        "currentGoals": 2,
        "topPct": 0.191,
        "tieSplitTopPct": 0.039
      },
      {
        "player": "Anthony Elanga",
        "team": "Sweden",
        "currentGoals": 2,
        "topPct": 0.188,
        "tieSplitTopPct": 0.03
      },
      {
        "player": "Yasin Ayari",
        "team": "Sweden",
        "currentGoals": 2,
        "topPct": 0.188,
        "tieSplitTopPct": 0.03
      },
      {
        "player": "Leandro Trossard",
        "team": "Belgium",
        "currentGoals": 2,
        "topPct": 0.174,
        "tieSplitTopPct": 0.038
      },
      {
        "player": "Ante Budimir",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 0.151,
        "tieSplitTopPct": 0.022
      },
      {
        "player": "Martin Baturina",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 0.151,
        "tieSplitTopPct": 0.022
      },
      {
        "player": "Petar Musa",
        "team": "Croatia",
        "currentGoals": 1,
        "topPct": 0.151,
        "tieSplitTopPct": 0.022
      },
      {
        "player": "Ramin Rezaeian",
        "team": "IR Iran",
        "currentGoals": 2,
        "topPct": 0.139,
        "tieSplitTopPct": 0.026
      },
      {
        "player": "Ayase Ueda",
        "team": "Japan",
        "currentGoals": 2,
        "topPct": 0.129,
        "tieSplitTopPct": 0.025
      },
      {
        "player": "Daichi Kamada",
        "team": "Japan",
        "currentGoals": 2,
        "topPct": 0.129,
        "tieSplitTopPct": 0.025
      },
      {
        "player": "Folarin Balogun",
        "team": "USA",
        "currentGoals": 2,
        "topPct": 0.129,
        "tieSplitTopPct": 0.028
      },
      {
        "player": "Nicolas Pépé",
        "team": "Côte d'Ivoire",
        "currentGoals": 2,
        "topPct": 0.09,
        "tieSplitTopPct": 0.022
      },
      {
        "player": "Caleb Yirenkyi",
        "team": "Ghana",
        "currentGoals": 1,
        "topPct": 0.085,
        "tieSplitTopPct": 0.017
      },
      {
        "player": "Marko Arnautović",
        "team": "Austria",
        "currentGoals": 1,
        "topPct": 0.064,
        "tieSplitTopPct": 0.011
      },
      {
        "player": "Romano Schmid",
        "team": "Austria",
        "currentGoals": 1,
        "topPct": 0.064,
        "tieSplitTopPct": 0.011
      },
      {
        "player": "Ermin Mahmić",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 2,
        "topPct": 0.057,
        "tieSplitTopPct": 0.013
      },
      {
        "player": "Amine Gouiri",
        "team": "Algeria",
        "currentGoals": 1,
        "topPct": 0.03,
        "tieSplitTopPct": 0.005
      },
      {
        "player": "Nadhir Benbouali",
        "team": "Algeria",
        "currentGoals": 1,
        "topPct": 0.03,
        "tieSplitTopPct": 0.005
      },
      {
        "player": "Yoane Wissa",
        "team": "DR Congo",
        "currentGoals": 1,
        "topPct": 0.025,
        "tieSplitTopPct": 0.005
      },
      {
        "player": "Ali Iyad Olwan",
        "team": "Jordan",
        "currentGoals": 1,
        "topPct": 0.002,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nizar Al-Rashdan",
        "team": "Jordan",
        "currentGoals": 1,
        "topPct": 0.002,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Abbosbek Fayzullayev",
        "team": "Uzbekistan",
        "currentGoals": 1,
        "topPct": 0.001,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Abdulelah Al-Amri",
        "team": "Saudi Arabia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Achraf Hakimi",
        "team": "Morocco",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Agustín Canobbio",
        "team": "Uruguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alex Freeman",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alexander Isak",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Alexis Saelemaekers",
        "team": "Belgium",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Amad Diallo",
        "team": "Côte d'Ivoire",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Arda Güler",
        "team": "Türkiye",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Auston Trusty",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ayman Hussein",
        "team": "Iraq",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Barış Alper Yılmaz",
        "team": "Türkiye",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Boualem Khoukhi",
        "team": "Qatar",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Bradley Barcola",
        "team": "France",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Breel Embolo",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Cody Gakpo",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Connor Metcalfe",
        "team": "Australia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Crysencio Summerville",
        "team": "Netherlands",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Cyle Larin",
        "team": "Canada",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Daizen Maeda",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Désiré Doué",
        "team": "France",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Elijah Just",
        "team": "New Zealand",
        "currentGoals": 3,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Emam Ashour",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Felix Nmecha",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ferran Torres",
        "team": "Spain",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Finn Surman",
        "team": "New Zealand",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Franck Kessié",
        "team": "Côte d'Ivoire",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gessime Yassine",
        "team": "Morocco",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gio Reyna",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gonzalo Plata",
        "team": "Ecuador",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Gonçalo Ramos",
        "team": "Portugal",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Granit Xhaka",
        "team": "Switzerland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Habib Diarra",
        "team": "Senegal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hassan Al-Haydos",
        "team": "Qatar",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hazem Mastouri",
        "team": "Tunisia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hwang In-beom",
        "team": "Korea Republic",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Hélio Varela",
        "team": "Cabo Verde",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ibrahim Mbaye",
        "team": "Senegal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Iliman Ndiaye",
        "team": "Senegal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jamal Musiala",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jaminton Campaz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jan Paul van Hecke",
        "team": "Netherlands",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "John McGinn",
        "team": "Scotland",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jovo Lukić",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "João Neves",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Jude Bellingham",
        "team": "England",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Julián Álvarez",
        "team": "Argentina",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Junya Itō",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kaan Ayhan",
        "team": "Türkiye",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kai Havertz",
        "team": "Germany",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Keito Nakamura",
        "team": "Japan",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kerim Alajbegovic",
        "team": "Bosnia-Herzegovina",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kevin De Bruyne",
        "team": "Belgium",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Kevin Pina",
        "team": "Cabo Verde",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ladislav Krejčí",
        "team": "Czechia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Lamine Yamal",
        "team": "Spain",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Leo Østigård",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Leroy Sané",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Livano Comenencia",
        "team": "Curaçao",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Luis Díaz",
        "team": "Colombia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Luis Romo",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mahmoud Saber",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Marcus Pedersen",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Marcus Rashford",
        "team": "England",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mateo Chávez",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Matheus Cunha",
        "team": "Brazil",
        "currentGoals": 3,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mattias Svanberg",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Matías Galarza",
        "team": "Paraguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mauricio",
        "team": "Paraguay",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Maxi Araújo",
        "team": "Uruguay",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Michael Olise",
        "team": "France",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Michal Sadílek",
        "team": "Czechia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mohamed Salah",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mohammad Mohebi",
        "team": "IR Iran",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Mostafa Zico",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nathan Saliba",
        "team": "Canada",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nathaniel Brown",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nestory Irankunda",
        "team": "Australia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nico Schlotterbeck",
        "team": "Germany",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nilson Angulo",
        "team": "Ecuador",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Nuno Mendes",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Oh Hyun-gyu",
        "team": "Korea Republic",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Omar Rekik",
        "team": "Tunisia",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Pape Gueye",
        "team": "Senegal",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Promise David",
        "team": "Canada",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Rafael Leão",
        "team": "Portugal",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Raphinha",
        "team": "Brazil",
        "currentGoals": 0,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Raúl Jiménez",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Romelu Lukaku",
        "team": "Belgium",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Ruben Vargas",
        "team": "Switzerland",
        "currentGoals": 2,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Sebastian Berhalter",
        "team": "USA",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Soufiane Rahimi",
        "team": "Morocco",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Thapelo Maseko",
        "team": "South Africa",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Thelo Aasgaard",
        "team": "Norway",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Trézéguet",
        "team": "Egypt",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Viktor Gyökeres",
        "team": "Sweden",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Virgil van Dijk",
        "team": "Netherlands",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Wilson Isidor",
        "team": "Haiti",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Álex Baena",
        "team": "Spain",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      },
      {
        "player": "Álvaro Fidalgo",
        "team": "Mexico",
        "currentGoals": 1,
        "topPct": 0.0,
        "tieSplitTopPct": 0.0
      }
    ],
    "missingParticipantPicks": []
  },
  "gallifantesPrizeSchedule": {
    "1": 750,
    "2": 250,
    "3": 100,
    "27": 20,
    "last": 20
  },
  "gallifantesSourceNote": "Computed directly from this 100,000-simulation distribution; ties split prizes for positions 1, 2, 3, 27, and last.",
  "lastPlaceNote": "lastPct is tie-split probability of finishing in the final position; ties for last split the last-place probability share.",
  "modelDetails": {
    "scoreModel": "empirical_recent_weighted_world_cup_scorelines",
    "recencyHalfLifeYears": 16.0,
    "baseYear": 2022,
    "source": "DataHub football/worldcup matches.csv sourced from Fjelstul World Cup Database; men only, 1930-2022",
    "groupDrawRatePct": 23.742,
    "knockoutDrawRatePct": 21.683
  },
  "deltaBaseline": "After Group I / M62, fresh 300,000 independent simulations",
  "deltaFields": [
    "winDeltaPp",
    "top3DeltaPp",
    "rankDelta"
  ],
  "conditionalChampionNote": "conditionalChampionWinPct = P(participant wins the porra | that participant’s projected champion wins the simulated World Cup), using tie-split porra wins.",
  "conditionalChampionTable": [
    {
      "rank": 1,
      "player": "Aleix",
      "displayName": "Aleix",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 74.478,
      "winCredit": 14172.333333333334
    },
    {
      "rank": 2,
      "player": "JoanRa",
      "displayName": "JoanRa",
      "projectedWinner": "Germany",
      "championWinSims": 20781,
      "conditionalWinPct": 64.847,
      "winCredit": 13475.833333333334
    },
    {
      "rank": 3,
      "player": "Rafa Bravo",
      "displayName": "Rafa B.",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 47.972,
      "winCredit": 15175.0
    },
    {
      "rank": 4,
      "player": "Andy",
      "displayName": "Andy",
      "projectedWinner": "Colombia",
      "championWinSims": 10456,
      "conditionalWinPct": 41.381,
      "winCredit": 4326.833333333334
    },
    {
      "rank": 5,
      "player": "Nicolau",
      "displayName": "Nicolau",
      "projectedWinner": "Brazil",
      "championWinSims": 17400,
      "conditionalWinPct": 40.814,
      "winCredit": 7101.666666666667
    },
    {
      "rank": 6,
      "player": "Carlo",
      "displayName": "Carlo",
      "projectedWinner": "England",
      "championWinSims": 22029,
      "conditionalWinPct": 38.566,
      "winCredit": 8495.666666666668
    },
    {
      "rank": 7,
      "player": "Joan",
      "displayName": "Joan",
      "projectedWinner": "Argentina",
      "championWinSims": 38288,
      "conditionalWinPct": 31.129,
      "winCredit": 11918.833333333332
    },
    {
      "rank": 8,
      "player": "Jordi Raventós",
      "displayName": "Jordi Ra.",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 30.302,
      "winCredit": 9585.333333333334
    },
    {
      "rank": 9,
      "player": "Oscar Bordas",
      "displayName": "Oscar B.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 14.059,
      "winCredit": 3501.416666666667
    },
    {
      "rank": 10,
      "player": "Chús",
      "displayName": "Chús",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 13.778,
      "winCredit": 3431.6666666666665
    },
    {
      "rank": 11,
      "player": "Bernat Orriols",
      "displayName": "Bernat O.",
      "projectedWinner": "Argentina",
      "championWinSims": 38288,
      "conditionalWinPct": 13.276,
      "winCredit": 5083.166666666666
    },
    {
      "rank": 12,
      "player": "Juanma",
      "displayName": "Juanma",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 12.892,
      "winCredit": 3210.916666666667
    },
    {
      "rank": 13,
      "player": "Jaume Cardús",
      "displayName": "Jaume C.",
      "projectedWinner": "Brazil",
      "championWinSims": 17400,
      "conditionalWinPct": 12.707,
      "winCredit": 2211.0
    },
    {
      "rank": 14,
      "player": "Oscar Campanyà",
      "displayName": "Oscar C.",
      "projectedWinner": "Argentina",
      "championWinSims": 38288,
      "conditionalWinPct": 12.179,
      "winCredit": 4662.916666666666
    },
    {
      "rank": 15,
      "player": "Miquel",
      "displayName": "Miquel",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 12.041,
      "winCredit": 2998.9166666666665
    },
    {
      "rank": 16,
      "player": "Bernat Garreta",
      "displayName": "Bernat G.",
      "projectedWinner": "England",
      "championWinSims": 22029,
      "conditionalWinPct": 10.495,
      "winCredit": 2312.0
    },
    {
      "rank": 17,
      "player": "Sergi Sanromà",
      "displayName": "Sergi S.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 8.487,
      "winCredit": 2113.666666666667
    },
    {
      "rank": 18,
      "player": "Pablo",
      "displayName": "Pablo",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 8.202,
      "winCredit": 1560.8333333333333
    },
    {
      "rank": 19,
      "player": "Rubi",
      "displayName": "Rubi",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 7.167,
      "winCredit": 1363.8333333333335
    },
    {
      "rank": 20,
      "player": "Marc",
      "displayName": "Marc",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 6.428,
      "winCredit": 1600.8333333333333
    },
    {
      "rank": 21,
      "player": "Antonio",
      "displayName": "Antonio",
      "projectedWinner": "Argentina",
      "championWinSims": 38288,
      "conditionalWinPct": 5.235,
      "winCredit": 2004.4999999999998
    },
    {
      "rank": 22,
      "player": "Emiliano",
      "displayName": "Emiliano",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 4.654,
      "winCredit": 1472.3333333333335
    },
    {
      "rank": 23,
      "player": "Oriol Valls",
      "displayName": "Oriol V.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 4.154,
      "winCredit": 1034.6666666666667
    },
    {
      "rank": 24,
      "player": "Pau",
      "displayName": "Pau",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 4.126,
      "winCredit": 1305.3333333333335
    },
    {
      "rank": 25,
      "player": "Guille Amor",
      "displayName": "Guille A.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 3.824,
      "winCredit": 952.3333333333333
    },
    {
      "rank": 26,
      "player": "Biel",
      "displayName": "Biel",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 3.297,
      "winCredit": 1043.0
    },
    {
      "rank": 27,
      "player": "Daniela",
      "displayName": "Daniela",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 2.854,
      "winCredit": 710.8333333333334
    },
    {
      "rank": 28,
      "player": "Bernat Raventós",
      "displayName": "Bernat R.",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 2.695,
      "winCredit": 852.5
    },
    {
      "rank": 29,
      "player": "Jordi Ollé",
      "displayName": "Jordi O.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 2.487,
      "winCredit": 619.5
    },
    {
      "rank": 30,
      "player": "Isra",
      "displayName": "Isra",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 2.374,
      "winCredit": 591.3333333333334
    },
    {
      "rank": 31,
      "player": "Oriol Oltra",
      "displayName": "Oriol O.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 2.121,
      "winCredit": 528.1666666666667
    },
    {
      "rank": 32,
      "player": "Xavi Ferrés",
      "displayName": "Xavi F.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 1.558,
      "winCredit": 388.0
    },
    {
      "rank": 33,
      "player": "Rafa Angulo",
      "displayName": "Rafa A.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 1.326,
      "winCredit": 330.25
    },
    {
      "rank": 34,
      "player": "Manu GS",
      "displayName": "Manu G.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 1.285,
      "winCredit": 320.0
    },
    {
      "rank": 35,
      "player": "Albert Cosí",
      "displayName": "Albert C.",
      "projectedWinner": "Argentina",
      "championWinSims": 38288,
      "conditionalWinPct": 1.228,
      "winCredit": 470.0
    },
    {
      "rank": 36,
      "player": "Martina",
      "displayName": "Martina",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 1.155,
      "winCredit": 287.6666666666667
    },
    {
      "rank": 37,
      "player": "Pol",
      "displayName": "Pol",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.983,
      "winCredit": 311.0
    },
    {
      "rank": 38,
      "player": "David Muñoz",
      "displayName": "David M.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.848,
      "winCredit": 211.08333333333331
    },
    {
      "rank": 39,
      "player": "Jordi Reig",
      "displayName": "Jordi Re.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.687,
      "winCredit": 171.0
    },
    {
      "rank": 40,
      "player": "Enrique Moral",
      "displayName": "Enrique M.",
      "projectedWinner": "Germany",
      "championWinSims": 20781,
      "conditionalWinPct": 0.585,
      "winCredit": 121.5
    },
    {
      "rank": 41,
      "player": "Paco",
      "displayName": "Paco",
      "projectedWinner": "Argentina",
      "championWinSims": 38288,
      "conditionalWinPct": 0.563,
      "winCredit": 215.5
    },
    {
      "rank": 42,
      "player": "Teo",
      "displayName": "Teo",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.556,
      "winCredit": 138.5
    },
    {
      "rank": 43,
      "player": "Michael",
      "displayName": "Michael",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.493,
      "winCredit": 156.0
    },
    {
      "rank": 44,
      "player": "Norber",
      "displayName": "Norber",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.359,
      "winCredit": 89.5
    },
    {
      "rank": 45,
      "player": "Toni Campanyà",
      "displayName": "Toni C.",
      "projectedWinner": "Brazil",
      "championWinSims": 17400,
      "conditionalWinPct": 0.241,
      "winCredit": 42.0
    },
    {
      "rank": 46,
      "player": "Albert Esteve",
      "displayName": "Albert E.",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 0.113,
      "winCredit": 21.5
    },
    {
      "rank": 47,
      "player": "Jaume Martí",
      "displayName": "Jaume M.",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 0.066,
      "winCredit": 12.5
    },
    {
      "rank": 48,
      "player": "Jordi Cunyao",
      "displayName": "Jordi C.",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.04,
      "winCredit": 12.5
    },
    {
      "rank": 49,
      "player": "Guillem Ochoa",
      "displayName": "Guillem O.",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.028,
      "winCredit": 7.0
    },
    {
      "rank": 50,
      "player": "Eduard Verdaguer",
      "displayName": "Eduard V.",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.016,
      "winCredit": 5.0
    },
    {
      "rank": 51,
      "player": "Pere",
      "displayName": "Pere",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.016,
      "winCredit": 4.0
    },
    {
      "rank": 52,
      "player": "Nick",
      "displayName": "Nick",
      "projectedWinner": "Spain",
      "championWinSims": 24906,
      "conditionalWinPct": 0.006,
      "winCredit": 1.5
    },
    {
      "rank": 53,
      "player": "Manel Pujol",
      "displayName": "Manel P.",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.003,
      "winCredit": 1.0
    },
    {
      "rank": 54,
      "player": "Albert Benach",
      "displayName": "Albert B.",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 0.0,
      "winCredit": 0.0
    },
    {
      "rank": 55,
      "player": "Andreu",
      "displayName": "Andreu",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.0,
      "winCredit": 0.0
    },
    {
      "rank": 56,
      "player": "Eduardo Morales",
      "displayName": "Eduardo M.",
      "projectedWinner": "Portugal",
      "championWinSims": 19029,
      "conditionalWinPct": 0.0,
      "winCredit": 0.0
    },
    {
      "rank": 57,
      "player": "Gerard",
      "displayName": "Gerard",
      "projectedWinner": "France",
      "championWinSims": 31633,
      "conditionalWinPct": 0.0,
      "winCredit": 0.0
    }
  ]
};
