// Final results used for Monte Carlo odds through Tunisia 0-4 Japan, 2026-06-21.
window.PORRA_RESULTATS = { matches: {
"G-A-1": { homeScore: 2, awayScore: 0, status: "FINISHED" }
,"G-A-2": { homeScore: 2, awayScore: 1, status: "FINISHED" }
,"G-A-3": { homeScore: 1, awayScore: 0, status: "FINISHED" }
,"G-A-4": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-B-1": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-B-2": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-B-3": { homeScore: 6, awayScore: 0, status: "FINISHED" }
,"G-B-4": { homeScore: 4, awayScore: 1, status: "FINISHED" }
,"G-C-1": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-C-2": { homeScore: 0, awayScore: 1, status: "FINISHED" }
,"G-C-3": { homeScore: 3, awayScore: 0, status: "FINISHED" }
,"G-C-4": { homeScore: 0, awayScore: 1, status: "FINISHED" }
,"G-D-1": { homeScore: 4, awayScore: 1, status: "FINISHED" }
,"G-D-2": { homeScore: 2, awayScore: 0, status: "FINISHED" }
,"G-D-3": { homeScore: 2, awayScore: 0, status: "FINISHED" }
,"G-D-4": { homeScore: 0, awayScore: 1, status: "FINISHED" }
,"G-E-1": { homeScore: 7, awayScore: 1, status: "FINISHED" }
,"G-E-2": { homeScore: 1, awayScore: 0, status: "FINISHED" }
,"G-E-3": { homeScore: 2, awayScore: 1, status: "FINISHED" }
,"G-E-4": { homeScore: 0, awayScore: 0, status: "FINISHED" }
,"G-F-1": { homeScore: 2, awayScore: 2, status: "FINISHED" }
,"G-F-2": { homeScore: 5, awayScore: 1, status: "FINISHED" }
,"G-F-3": { homeScore: 5, awayScore: 1, status: "FINISHED" }
,"G-F-4": { homeScore: 0, awayScore: 4, status: "FINISHED" }
,"G-G-1": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-G-2": { homeScore: 2, awayScore: 2, status: "FINISHED" }
,"G-H-1": { homeScore: 0, awayScore: 0, status: "FINISHED" }
,"G-H-2": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-I-1": { homeScore: 3, awayScore: 1, status: "FINISHED" }
,"G-I-2": { homeScore: 1, awayScore: 4, status: "FINISHED" }
,"G-J-1": { homeScore: 3, awayScore: 0, status: "FINISHED" }
,"G-J-2": { homeScore: 3, awayScore: 1, status: "FINISHED" }
,"G-K-1": { homeScore: 1, awayScore: 1, status: "FINISHED" }
,"G-K-2": { homeScore: 1, awayScore: 3, status: "FINISHED" }
,"G-L-1": { homeScore: 4, awayScore: 2, status: "FINISHED" }
,"G-L-2": { homeScore: 1, awayScore: 0, status: "FINISHED" }
}};
