name: Schedule test

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Current UTC time: $(date -u)"
